"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1";
function env(){const out={};for(const line of fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/)){const m=line.match(/^([^#=]+)=(.*)$/);if(m)out[m[1].trim()]=m[2];}return out;}
async function api(route,key,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":key,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`API ${response.status} ${route}: ${body.slice(0,500)}`);return body?JSON.parse(body):{};}
async function main(){const output=process.argv[2];if(!output)throw new Error("output path required");const e=env(),reference=await api("/workflows/AffWaDelivery2026",e.N8N_API_KEY);const credential=reference.nodes.map(n=>n.credentials?.googleSheetsOAuth2Api).find(Boolean);const route=`delivery-core-audit-${crypto.randomUUID()}`,base=`https://sheets.googleapis.com/v4/spreadsheets/${e.AFFILIATE_TRACKER_SPREADSHEET_ID}/values/`;
const http=(name,url,x)=>({parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:base+url,options:{timeout:45000}},id:crypto.randomUUID(),name,type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[x,0],credentials:{googleSheetsOAuth2Api:credential}});
const code=`function t(v){return v==null?"":String(v).trim()} function rows(v){const h=(v?.[0]||[]).map(t);return (v||[]).slice(1).map((r,i)=>({row_number:i+2,...Object.fromEntries(h.map((n,c)=>[n,t(r[c])]))}))} const folders=new Set(["6901","6902","6903","6904","6905","6906","6907"]),numbers=new Set(["6289508881998","6289656262493","6285782000199","6285710416787","6282329499945","6281802341011","6285864300358"]),digits=v=>t(v).replace(/\\D/g,"");const leads=rows($("Read Leads Core").first().json.values),delivery=rows($("Read Delivery Core").first().json.values),messages=rows($("Read Messages Core").first().json.values);const affectedLeads=leads.filter(r=>folders.has(r.batch_number)||numbers.has(digits(r.wa_id||r.whatsapp_number))),conversations=new Set(affectedLeads.map(r=>r.conversation_id));return [{json:{audited_at:new Date().toISOString(),leads:affectedLeads,delivery_log:delivery.filter(r=>folders.has(r.batch_number)||conversations.has(r.conversation_id)),message_log:messages.filter(r=>numbers.has(digits(r.recipient_number||r.whatsapp_number||r.wa_id))||conversations.has(r.conversation_id)||folders.has(r.batch_number))}}]`;
const nodes=[{parameters:{httpMethod:"GET",path:route,responseMode:"lastNode",options:{}},id:crypto.randomUUID(),name:"Core Audit",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-500,0],webhookId:crypto.randomUUID()},http("Read Leads Core","WhatsApp%20Leads!A%3AAE",-300),http("Read Delivery Core","Delivery%20Log!A%3AR",-100),http("Read Messages Core","WhatsApp%20Message%20Log!A%3AX",100),{parameters:{jsCode:code},id:crypto.randomUUID(),name:"Return Core Audit",type:"n8n-nodes-base.code",typeVersion:2,position:[300,0]}];const connections={"Core Audit":{main:[[{node:"Read Leads Core",type:"main",index:0}]]},"Read Leads Core":{main:[[{node:"Read Delivery Core",type:"main",index:0}]]},"Read Delivery Core":{main:[[{node:"Read Messages Core",type:"main",index:0}]]},"Read Messages Core":{main:[[{node:"Return Core Audit",type:"main",index:0}]]}};
const workflow=await api("/workflows",e.N8N_API_KEY,{method:"POST",body:JSON.stringify({name:"Temporary Core Delivery Audit",nodes,connections,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all"}})});try{await api(`/workflows/${workflow.id}/activate`,e.N8N_API_KEY,{method:"POST"});const response=await fetch(`http://localhost:5678/webhook/${route}`);const body=await response.text();if(!response.ok)throw new Error(`audit ${response.status}: ${body.slice(0,500)}`);const data=JSON.parse(body);fs.writeFileSync(output,JSON.stringify(data,null,2)+"\n");process.stdout.write(JSON.stringify({audited_at:data.audited_at,leads:data.leads.length,delivery:data.delivery_log.length,messages:data.message_log.length},null,2)+"\n");}finally{try{await api(`/workflows/${workflow.id}/deactivate`,e.N8N_API_KEY,{method:"POST"});}catch{}await api(`/workflows/${workflow.id}`,e.N8N_API_KEY,{method:"DELETE"});}}
main().catch(e=>{process.stderr.write((e.stack||e.message)+"\n");process.exitCode=1;});
