"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",CORE="1eyA1XRNZU0usuii801IrJCJHp8oCh2XjlfROrzzvpwE",SIMPLE="1Zsq-ngyC1RGOCLlibFI-UyPBW88oQc0aJhC5cxtbrzA";
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map(line=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""]}).filter(([key])=>key));
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}}),body=await response.text();if(!response.ok)throw new Error(`n8n_${response.status}:${route}:${body.slice(0,500)}`);return body?JSON.parse(body):{}}
const id=()=>crypto.randomUUID(),edge=node=>({main:[[{node,type:"main",index:0}]]});
(async()=>{const output=process.argv[2];if(!output)throw new Error("output path required");const delivery=await api("/workflows/AffWaDelivery2026"),credential=delivery.nodes.map(node=>node.credentials?.googleSheetsOAuth2Api).find(Boolean),route=`recent-assignment-audit-${id()}`;
const req=(name,sheet,range,x)=>({id:id(),name,type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[x,0],credentials:{googleSheetsOAuth2Api:credential},parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${sheet}/values/${range}`,options:{timeout:45000}}});
const nodes=[{id:id(),name:"Request",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-700,0],webhookId:id(),parameters:{httpMethod:"GET",path:route,responseMode:"lastNode",options:{}}},req("Leads",CORE,"WhatsApp%20Leads!A%3AAF",-500),req("Delivery",CORE,"Delivery%20Log!A%3AR",-300),req("Simple",SIMPLE,"%27Delivery%20Log%27!A%3AG",-100),{id:id(),name:"Summarize",type:"n8n-nodes-base.code",typeVersion:2,position:[100,0],parameters:{jsCode:`const t=v=>v==null?"":String(v).trim();function table(v){const h=(v?.[0]||[]).map(t);return(v||[]).slice(1).map((r,i)=>({row_number:i+2,...Object.fromEntries(h.map((n,c)=>[n,t(r[c])]))}))}const leads=table($("Leads").first().json.values),delivery=table($("Delivery").first().json.values),simple=table($("Simple").first().json.values),out=[];for(const row of simple){const batch=t(row["Numbered Folder"]);if(!/^\\d+$/.test(batch)||Number(batch)<6916)continue;const lead=leads.find(r=>t(r.batch_number)===batch),detail=delivery.filter(r=>t(r.batch_number)===batch),wamids=detail.map(r=>t(r.whatsapp_message_id)).filter(Boolean);out.push({batch,username:row.Username,phone:row["WhatsApp Number"],simple_row:row.row_number,simple_clips:row["Clips Sent"],simple_status:row.Status,simple_error:row.Error,lead_row:lead?.row_number||"",delivery_state:lead?.delivery_state||"",files_expected:lead?.files_expected||"",files_sent:lead?.files_sent||"",files_failed:lead?.files_failed||"",delivery_started_at:lead?.delivery_started_at||"",detail_rows:detail.length,accepted_rows:detail.filter(r=>["accepted","sent","delivered","read"].includes(t(r.state||r.send_state||r.delivery_state))).length,distinct_wamids:new Set(wamids).size,attempts:[...new Set(detail.map(r=>t(r.attempts)).filter(Boolean))]})}return[{json:{audited_at:new Date().toISOString(),assignments:out}}];`}}];
const connections={};for(let i=0;i<nodes.length-1;i++)connections[nodes[i].name]=edge(nodes[i+1].name);const workflow=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Temporary Recent Fresh Assignment History Audit",nodes,connections,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all"}})});try{await api(`/workflows/${workflow.id}/activate`,{method:"POST"});const response=await fetch(`http://localhost:5678/webhook/${route}`),body=await response.text();if(!response.ok)throw new Error(`audit_${response.status}:${body.slice(0,500)}`);const result=JSON.parse(body);fs.writeFileSync(output,JSON.stringify(result,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(result,null,2)+"\n")}finally{try{await api(`/workflows/${workflow.id}/deactivate`,{method:"POST"})}catch{}try{await api(`/workflows/${workflow.id}`,{method:"DELETE"})}catch{}}})().catch(error=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1});
