"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),OUT=path.join(ROOT,"n8n","exports","fresh-production-incident-6945-6947-20260828","deployment"),API="http://localhost:5678/api/v1",ID="AffWaDelivery2026",EXPECTED_VERSION="73ad63f9-dcc2-41c2-a607-96e2244b229c",PAUSED_CALLER="__delivery_recovery_paused__";
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map(line=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""]}).filter(([key])=>key));
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}const hash=v=>crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex"),definition=w=>({name:w.name,nodes:w.nodes,connections:w.connections,settings:w.settings});
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}}),body=await response.text();if(!response.ok)throw new Error(`n8n_${response.status}:${route}:${body.slice(0,800)}`);return body?JSON.parse(body):{}}
function payload(w){const allowed=["saveExecutionProgress","saveManualExecutions","saveDataErrorExecution","saveDataSuccessExecution","executionTimeout","errorWorkflow","timezone","executionOrder","callerPolicy","callerIds","timeSavedPerExecution","redactionPolicy","availableInMCP","customTelemetryTags"];return{name:w.name,nodes:w.nodes,connections:w.connections,settings:Object.fromEntries(allowed.filter(k=>Object.hasOwn(w.settings||{},k)).map(k=>[k,w.settings[k]]))}}
(async()=>{fs.mkdirSync(OUT,{recursive:true});const before=await api(`/workflows/${ID}`);if(!before.active||before.versionId!==EXPECTED_VERSION||before.activeVersionId!==EXPECTED_VERSION)throw new Error("unexpected_live_delivery_version");if(before.settings?.callerIds!==PAUSED_CALLER)throw new Error("delivery_dispatch_not_paused");if(!before.nodes.some(n=>n.name==="Prepare Assignment Final Log")||!before.nodes.some(n=>n.name==="Done: Delivery Send Attempt"))throw new Error("required_final_nodes_missing");const done=(before.connections?.["Done: Delivery Send Attempt"]?.main||[]).flat();if(done.length)throw new Error("root_defect_not_present_or_definition_changed");const beforeHash=hash(definition(before)),nodeHash=hash(before.nodes),settingsHash=hash(before.settings);fs.writeFileSync(path.join(OUT,"AffWaDelivery2026.before.json"),JSON.stringify(before,null,2)+"\n",{mode:0o600});
before.connections["Done: Delivery Send Attempt"]={main:[[{node:"Prepare Assignment Final Log",type:"main",index:0}]]};await api(`/workflows/${ID}`,{method:"PUT",body:JSON.stringify(payload(before))});await api(`/workflows/${ID}/activate`,{method:"POST"});const after=await api(`/workflows/${ID}`),afterEdges=(after.connections?.["Done: Delivery Send Attempt"]?.main||[]).flat();if(!after.active||after.activeVersionId!==after.versionId)throw new Error("delivery_not_active_after_deploy");if(after.settings?.callerIds!==PAUSED_CALLER||hash(after.settings)!==settingsHash)throw new Error("dispatch_pause_or_settings_changed");if(hash(after.nodes)!==nodeHash)throw new Error("node_definition_changed");if(afterEdges.length!==1||afterEdges[0].node!=="Prepare Assignment Final Log"||afterEdges[0].index!==0)throw new Error("final_logger_connection_not_verified");const afterHash=hash(definition(after)),report={deployed_at:new Date().toISOString(),workflow_id:ID,before:{version_id:EXPECTED_VERSION,definition_sha256:beforeHash,active:true,caller_ids:PAUSED_CALLER},change:{source:"Done: Delivery Send Attempt",destination:"Prepare Assignment Final Log",branch:0,node_changes:0,other_connection_changes:0},after:{version_id:after.versionId,active_version_id:after.activeVersionId,definition_sha256:afterHash,active:after.active,caller_ids:after.settings?.callerIds},dispatch_remains_paused:true};fs.writeFileSync(path.join(OUT,"AffWaDelivery2026.after.json"),JSON.stringify(after,null,2)+"\n",{mode:0o600});fs.writeFileSync(path.join(OUT,"deployment-report.json"),JSON.stringify(report,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(report,null,2)+"\n")})().catch(error=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1});
