"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),OUT=path.join(ROOT,"n8n","exports","assignment-6944-readback-recovery-20260824"),API="http://localhost:5678/api/v1",ID="AffWaDelivery2026";
const APPLY=process.argv.includes("--apply"),EXPECTED_VERSION="0e41e3cc-036a-4903-adcc-068e4039037a",EXPECTED_HASH="ab8c45c5900e15d1febaa897871dc580c17b69fcd60f6c94c734706444327106";
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map((line)=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""];}).filter(([key])=>key));
const ALLOWED_SETTINGS=["saveExecutionProgress","saveManualExecutions","saveDataErrorExecution","saveDataSuccessExecution","executionTimeout","errorWorkflow","timezone","executionOrder","callerPolicy","callerIds","timeSavedPerExecution","redactionPolicy","availableInMCP","customTelemetryTags"];
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map((k)=>[k,stable(v[k])]));return v;}const hash=(v)=>crypto.createHash("sha256").update(JSON.stringify(stable(v))).digest("hex");
const definition=(w)=>({name:w.name,nodes:w.nodes,connections:w.connections,settings:w.settings});
const nodeDefinition=(n)=>({type:n.type,typeVersion:n.typeVersion,parameters:n.parameters,credentials:n.credentials,retryOnFail:n.retryOnFail,maxTries:n.maxTries,waitBetweenTries:n.waitBetweenTries,continueOnFail:n.continueOnFail,onError:n.onError,disabled:n.disabled});
const payload=(w)=>({name:w.name,nodes:w.nodes,connections:w.connections,settings:Object.fromEntries(ALLOWED_SETTINGS.filter((k)=>Object.hasOwn(w.settings||{},k)).map((k)=>[k,w.settings[k]]))});
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`n8n_${response.status}:${route}:${body.slice(0,500)}`);return body?JSON.parse(body):{};}
(async()=>{
 const before=await api(`/workflows/${ID}`);if(before.versionId!==EXPECTED_VERSION||hash(definition(before))!==EXPECTED_HASH)throw new Error("delivery_changed_since_backup");if(!before.active||before.activeVersionId!==before.versionId)throw new Error("delivery_not_active_expected_version");
 const proposed=structuredClone(before),persist="Persist Successful Clip Immediately",read="Read Back Persisted Successful Clip",guard="Prepare Successful Clip Read-Back Target";
 if(proposed.nodes.some((n)=>n.name===guard))throw new Error("guard_already_exists");
 const readNode=proposed.nodes.find((n)=>n.name===read),persistNode=proposed.nodes.find((n)=>n.name===persist);if(!readNode||!persistNode)throw new Error("immediate_nodes_missing");
 proposed.nodes.push({id:crypto.randomUUID(),name:guard,type:"n8n-nodes-base.code",typeVersion:2,position:[persistNode.position[0]+220,persistNode.position[1]],parameters:{jsCode:fs.readFileSync(path.join(ROOT,"n8n","code","prepare-successful-clip-readback-target.js"),"utf8")}});
 readNode.position=[readNode.position[0]+220,readNode.position[1]];readNode.parameters.url="={{ $json.successful_clip_readback_url }}";
 const persistEdges=proposed.connections[persist]?.main?.[0]||[];if(persistEdges.length!==1||persistEdges[0].node!==read)throw new Error("unexpected_persist_connection");
 proposed.connections[persist].main[0]=[{node:guard,type:"main",index:0}];proposed.connections[guard]={main:[[{node:read,type:"main",index:0}]]};
 const beforeHashes=Object.fromEntries(before.nodes.map((n)=>[n.name,hash(nodeDefinition(n))])),afterHashes=Object.fromEntries(proposed.nodes.map((n)=>[n.name,hash(nodeDefinition(n))]));
 const changed=Object.keys(beforeHashes).filter((name)=>beforeHashes[name]!==afterHashes[name]),added=Object.keys(afterHashes).filter((name)=>!beforeHashes[name]);
 if(JSON.stringify(changed)!==JSON.stringify([read])||JSON.stringify(added)!==JSON.stringify([guard]))throw new Error(`unexpected_node_delta:${changed}:${added}`);
 let after=proposed;if(APPLY){await api(`/workflows/${ID}`,{method:"PUT",body:JSON.stringify(payload(proposed))});await api(`/workflows/${ID}/activate`,{method:"POST"});after=await api(`/workflows/${ID}`);}
 const report={mode:APPLY?"applied":"dry_run",captured_at:new Date().toISOString(),before:{version_id:before.versionId,hash:hash(definition(before))},proposed:{hash:hash(definition(proposed)),changed_nodes:changed,added_nodes:added,connections_changed:hash(before.connections)!==hash(proposed.connections)},after:{version_id:after.versionId,active_version_id:after.activeVersionId||"",active:after.active,hash:hash(definition(after))},integrity:{settings_unchanged:hash(before.settings)===hash(after.settings),credentials_unchanged:hash(before.nodes.map((n)=>({name:n.name,credentials:n.credentials||{}})))===hash(after.nodes.filter((n)=>n.name!==guard).map((n)=>({name:n.name,credentials:n.credentials||{}}))),caller_permissions_unchanged:before.settings?.callerPolicy===after.settings?.callerPolicy&&String(before.settings?.callerIds||"")===String(after.settings?.callerIds||""),meta_upload_unchanged:beforeHashes["Upload Video to WhatsApp"]===Object.fromEntries(after.nodes.map((n)=>[n.name,hash(nodeDefinition(n))]))["Upload Video to WhatsApp"],meta_send_unchanged:beforeHashes["Send WhatsApp Video"]===Object.fromEntries(after.nodes.map((n)=>[n.name,hash(nodeDefinition(n))]))["Send WhatsApp Video"]}};
 if(APPLY&&(!report.after.active||after.activeVersionId!==after.versionId||!report.integrity.settings_unchanged||!report.integrity.credentials_unchanged||!report.integrity.caller_permissions_unchanged||!report.integrity.meta_upload_unchanged||!report.integrity.meta_send_unchanged))throw new Error("post_deploy_integrity_failed");
 fs.writeFileSync(path.join(OUT,APPLY?"AffWaDelivery2026.after.json":"AffWaDelivery2026.proposed.json"),JSON.stringify(after,null,2)+"\n",{mode:0o600});fs.writeFileSync(path.join(OUT,APPLY?"deployment-report.json":"proposal-report.json"),JSON.stringify(report,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(report,null,2)+"\n");
})().catch((e)=>{process.stderr.write(`${e.stack||e.message}\n`);process.exitCode=1;});
