"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",ID="AffWaReply2026",NODE="Aggregate Delivery Status";
const ALLOWED=["saveExecutionProgress","saveManualExecutions","saveDataErrorExecution","saveDataSuccessExecution","executionTimeout","errorWorkflow","timezone","executionOrder","callerPolicy","callerIds","timeSavedPerExecution","redactionPolicy","availableInMCP","customTelemetryTags"];
function env(){const out={};for(const line of fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/)){const m=line.match(/^([^#=]+)=(.*)$/);if(m)out[m[1].trim()]=m[2];}return out;}
function hash(v){return crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");}
async function api(route,key,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":key,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`API ${response.status}: ${body.slice(0,500)}`);return body?JSON.parse(body):{};}
function payload(w){return{name:w.name,nodes:w.nodes,connections:w.connections,settings:Object.fromEntries(ALLOWED.filter(n=>Object.hasOwn(w.settings||{},n)).map(n=>[n,w.settings[n]]))};}
async function main(){const key=env().N8N_API_KEY,desired=JSON.parse(fs.readFileSync(path.join(ROOT,"n8n","imports","affiliate-whatsapp-reply-status.json"),"utf8")),live=await api(`/workflows/${ID}`,key),source=desired.nodes.find(n=>n.name===NODE),target=live.nodes.find(n=>n.name===NODE);if(!source||!target)throw new Error("aggregate node missing");const beforeCode=target.parameters.jsCode;if(!source.parameters.jsCode.includes('new Map()')||!source.parameters.jsCode.includes('["delivered", "read"]'))throw new Error("unsafe aggregate source");target.parameters={...target.parameters,jsCode:source.parameters.jsCode};const before={version:live.versionId,activeVersion:live.activeVersionId,active:live.active,nodeCount:live.nodes.length,hash:hash(beforeCode)};await api(`/workflows/${ID}`,key,{method:"PUT",body:JSON.stringify(payload(live))});if(before.active)await api(`/workflows/${ID}/activate`,key,{method:"POST"});const after=await api(`/workflows/${ID}`,key),afterNode=after.nodes.find(n=>n.name===NODE);if(after.nodes.length!==before.nodeCount||afterNode?.parameters?.jsCode!==source.parameters.jsCode||Boolean(after.active)!==Boolean(before.active))throw new Error("reply aggregate deploy verification failed");process.stdout.write(JSON.stringify({id:ID,node:NODE,before,after:{version:after.versionId,activeVersion:after.activeVersionId,active:after.active,nodeCount:after.nodes.length,hash:hash(afterNode.parameters.jsCode)}},null,2)+"\n");}
main().catch(e=>{process.stderr.write((e.stack||e.message)+"\n");process.exitCode=1;});
