"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1";
const EVIDENCE={
  "14136":{batch_number:"6905",conversation_id:"wa:6282329499945",whatsapp_number:"6282329499945",file_index:"8",file_name:"2026_06_03_11_52_23_run_191__2026_06_03_11_52_23_run_191_clip_0003_v0_original_score9_PENGALAMAN_KULIT_TAMPAK_LEBIH_CERAH.mp4",media_id:"1749869189656946"}
};
function env(){const out={};for(const line of fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/)){const m=line.match(/^([^#=]+)=(.*)$/);if(m)out[m[1].trim()]=m[2];}return out;}
async function api(route,key,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":key,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`API ${response.status}: ${body.slice(0,500)}`);return body?JSON.parse(body):{};}
async function main(){const arg=process.argv.find(a=>a.startsWith("--execution=")),id=arg?.slice(12),evidence=EVIDENCE[id];if(!evidence)throw new Error("execution upload evidence is not allowlisted");evidence.delivery_key=`${evidence.conversation_id}:${evidence.batch_number}:${evidence.file_name}`;const e=env(),reference=await api("/workflows/AffWaDelivery2026",e.N8N_API_KEY),credential=reference.nodes.map(n=>n.credentials?.googleSheetsOAuth2Api).find(Boolean),route=`reconcile-upload-${crypto.randomUUID()}`;
const code=`function t(v){return v==null?"":String(v).trim()} const evidence=${JSON.stringify(evidence)},values=$json.values||[],headers=(values[0]||[]).map(t),rows=values.slice(1).map((r,i)=>({row_number:i+2,...Object.fromEntries(headers.map((n,c)=>[n,t(r[c])]))}));if(rows.some(r=>r.delivery_key===evidence.delivery_key||r.media_id===evidence.media_id))throw new Error("upload_evidence_already_logged_or_conflicting");const now=new Date().toISOString(),record={delivery_key:evidence.delivery_key,conversation_id:evidence.conversation_id,whatsapp_number:evidence.whatsapp_number,batch_number:evidence.batch_number,file_index:evidence.file_index,file_name:evidence.file_name,media_id:evidence.media_id,whatsapp_message_id:"",state:"upload_ready_no_message",attempts:"1",uploaded_at:now,sent_at:"",delivered_at:"",failed_at:"",last_error:"execution_${id}_stopped_before_video_message",updated_at:now,send_state:"upload_ready_no_message",delivery_state:""};return [{json:{row_values:headers.map(n=>t(record[n])),evidence:{execution_id:"${id}",batch_number:evidence.batch_number,delivery_key:evidence.delivery_key,media_id:evidence.media_id}}}]`;
const workflow=await api("/workflows",e.N8N_API_KEY,{method:"POST",body:JSON.stringify({name:"Temporary Reconcile Uploaded Media",nodes:[{parameters:{httpMethod:"POST",path:route,responseMode:"lastNode",options:{}},id:crypto.randomUUID(),name:"Request",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-400,0],webhookId:crypto.randomUUID()},{parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${e.AFFILIATE_TRACKER_SPREADSHEET_ID}/values/Delivery%20Log!A:R`,options:{}},id:crypto.randomUUID(),name:"Read Delivery",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[-200,0],credentials:{googleSheetsOAuth2Api:credential}},{parameters:{jsCode:code},id:crypto.randomUUID(),name:"Validate Exact Upload",type:"n8n-nodes-base.code",typeVersion:2,position:[0,0]},{parameters:{method:"POST",url:`https://sheets.googleapis.com/v4/spreadsheets/${e.AFFILIATE_TRACKER_SPREADSHEET_ID}/values/Delivery%20Log!A:R:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",sendBody:true,specifyBody:"json",jsonBody:'={{ JSON.stringify({majorDimension:"ROWS",values:[$json.row_values]}) }}',options:{}},id:crypto.randomUUID(),name:"Append Upload Evidence",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[200,0],credentials:{googleSheetsOAuth2Api:credential}},{parameters:{jsCode:'return [{json:$("Validate Exact Upload").first().json.evidence}];'},id:crypto.randomUUID(),name:"Result",type:"n8n-nodes-base.code",typeVersion:2,position:[400,0]}],connections:{Request:{main:[[{node:"Read Delivery",type:"main",index:0}]]},"Read Delivery":{main:[[{node:"Validate Exact Upload",type:"main",index:0}]]},"Validate Exact Upload":{main:[[{node:"Append Upload Evidence",type:"main",index:0}]]},"Append Upload Evidence":{main:[[{node:"Result",type:"main",index:0}]]}},settings:{executionOrder:"v1",saveDataSuccessExecution:"none",saveDataErrorExecution:"all"}})});try{await api(`/workflows/${workflow.id}/activate`,e.N8N_API_KEY,{method:"POST"});const response=await fetch(`http://localhost:5678/webhook/${route}`,{method:"POST"}),body=await response.text();if(!response.ok)throw new Error(`reconcile ${response.status}: ${body.slice(0,500)}`);process.stdout.write(JSON.stringify(JSON.parse(body),null,2)+"\n");}finally{try{await api(`/workflows/${workflow.id}/deactivate`,e.N8N_API_KEY,{method:"POST"});}catch{}await api(`/workflows/${workflow.id}`,e.N8N_API_KEY,{method:"DELETE"});}}
main().catch(e=>{process.stderr.write((e.stack||e.message)+"\n");process.exitCode=1;});
