"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",PHONE="6281315350476",CONVERSATION="7563590806193226002",BATCH="6915";
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map(line=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""]}).filter(([k])=>k));
async function api(route,options={}){const r=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}}),body=await r.text();if(!r.ok)throw new Error(`API ${r.status} ${route}: ${body.slice(0,800)}`);return body?JSON.parse(body):{}}
async function main(){
 const reference=await api("/workflows/AffWaDelivery2026"),credential=reference.nodes.map(n=>n.credentials?.googleSheetsOAuth2Api).find(Boolean);if(!credential)throw new Error("Sheets credential missing");
 const route=`reconcile-ohyahahaa-6915-${crypto.randomUUID()}`,base=`https://sheets.googleapis.com/v4/spreadsheets/${env.AFFILIATE_TRACKER_SPREADSHEET_ID}`;
 const ranges=["WhatsApp Leads!A:AE","Delivery Log!A:R","WhatsApp Message Log!A:X"],query=ranges.map(r=>`ranges=${encodeURIComponent(r)}`).join("&");
 const code=`function t(v){return v==null?"":String(v).trim()}function table(r){const v=r?.values||[],h=(v[0]||[]).map(t);return{h,rows:v.slice(1).map((x,i)=>({row_number:i+2,...Object.fromEntries(h.map((n,c)=>[n,t(x[c])]))}))}}const ranges=$json.valueRanges||[],leads=table(ranges[0]),delivery=table(ranges[1]),messages=table(ranges[2]);const lead=leads.rows.find(r=>r.row_number===51);if(!lead||lead.username!=="ohyahahaa"||t(lead.wa_id||lead.whatsapp_number).replace(/\\D/g,"")!==${JSON.stringify(PHONE)}||lead.conversation_id!==${JSON.stringify(CONVERSATION)}||lead.batch_number!==${JSON.stringify(BATCH)})throw new Error("canonical_lead_51_changed");if(lead.last_error)throw new Error("migration_marker_or_error_not_consumed_cleanly");const d=delivery.rows.filter(r=>r.conversation_id===${JSON.stringify(CONVERSATION)}&&r.batch_number===${JSON.stringify(BATCH)}),m=messages.rows.filter(r=>r.recipient_number===${JSON.stringify(PHONE)}&&t(r.source_reference).startsWith(${JSON.stringify(CONVERSATION+":"+BATCH+":")}));const ids=d.map(r=>r.whatsapp_message_id).filter(Boolean),mids=m.map(r=>r.whatsapp_message_id).filter(Boolean);if(d.length!==15||m.length!==15||new Set(ids).size!==15||new Set(mids).size!==15||ids.some(id=>!mids.includes(id)))throw new Error("verified_log_pair_count_mismatch");if(d.some(r=>!["accepted","sent","delivered","read"].includes(r.delivery_state||r.state||r.send_state)||r.failed_at||r.last_error))throw new Error("delivery_contains_failure_or_unaccepted_clip");const delivered=d.filter(r=>["delivered","read"].includes(r.delivery_state||r.state)).length,now=new Date().toISOString(),sentAt=d.map(r=>r.sent_at).filter(Boolean).sort().at(-1)||now,record={...lead,state:"files_sent",files_expected:"15",files_sent:"15",files_delivered:String(delivered),files_failed:"0",files_sent_at:lead.files_sent_at||sentAt,last_error:"",updated_at:now};return[{json:{row_values:leads.h.map(n=>t(record[n])),summary:{row_number:51,state:record.state,batch_number:record.batch_number,files_sent:record.files_sent,files_delivered:record.files_delivered,files_failed:record.files_failed,allowance_state:record.last_error,message_ids:ids}}}];`;
 const verify=`const s=$("Prepare Verified Lead Repair").first().json.summary,v=$json.values||[],h=(v[0]||[]).map(x=>String(x??"").trim()),row=v[50]||[],get=n=>String(row[h.indexOf(n)]??"").trim();const out={...s,verified_state:get("state"),verified_batch:get("batch_number"),verified_files_sent:get("files_sent"),verified_files_delivered:get("files_delivered"),verified_files_failed:get("files_failed"),verified_allowance_state:get("last_error")};if(out.verified_state!=="files_sent"||out.verified_batch!=="6915"||out.verified_files_sent!=="15"||out.verified_files_failed!=="0"||out.verified_allowance_state!=="")throw new Error("fresh_lead_verification_failed:"+JSON.stringify(out));return[{json:out}];`;
 const trigger={id:crypto.randomUUID(),name:"Repair Request",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-500,0],parameters:{httpMethod:"POST",path:route,responseMode:"lastNode",options:{}},webhookId:crypto.randomUUID()},read={id:crypto.randomUUID(),name:"Fresh Verified Logs",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[-300,0],parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`${base}/values:batchGet?${query}`,options:{}},credentials:{googleSheetsOAuth2Api:credential}},prepare={id:crypto.randomUUID(),name:"Prepare Verified Lead Repair",type:"n8n-nodes-base.code",typeVersion:2,position:[-100,0],parameters:{jsCode:code}},write={id:crypto.randomUUID(),name:"Write Canonical Lead 51",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[100,0],parameters:{method:"PUT",authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`${base}/values/WhatsApp%20Leads!A51%3AAE51?valueInputOption=RAW`,sendBody:true,specifyBody:"json",jsonBody:'={{ JSON.stringify({majorDimension:"ROWS",values:[$json.row_values]}) }}',options:{}},credentials:{googleSheetsOAuth2Api:credential}},reread={id:crypto.randomUUID(),name:"Fresh Lead Verification",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[300,0],parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`${base}/values/WhatsApp%20Leads!A%3AAE`,options:{}},credentials:{googleSheetsOAuth2Api:credential}},result={id:crypto.randomUUID(),name:"Verified Result",type:"n8n-nodes-base.code",typeVersion:2,position:[500,0],parameters:{jsCode:verify}},nodes=[trigger,read,prepare,write,reread,result],connections={};for(let i=0;i<nodes.length-1;i++)connections[nodes[i].name]={main:[[{node:nodes[i+1].name,type:"main",index:0}]]};
 const w=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Temporary Reconcile ohyahahaa Batch 6915 Lead",nodes,connections,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all"}})});try{await api(`/workflows/${w.id}/activate`,{method:"POST"});const r=await fetch(`http://localhost:5678/webhook/${route}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}),body=await r.text();if(!r.ok)throw new Error(`repair ${r.status}: ${body.slice(0,800)}`);process.stdout.write(JSON.stringify({workflow_id:w.id,result:JSON.parse(body)},null,2)+"\n")}finally{try{await api(`/workflows/${w.id}/deactivate`,{method:"POST"})}catch{}try{await api(`/workflows/${w.id}`,{method:"DELETE"})}catch{}}
}
main().catch(e=>{process.stderr.write((e.stack||e.message)+"\n");process.exitCode=1});
