"use strict";
const fs=require("node:fs"),sqlite3=require("/usr/local/lib/node_modules/n8n/node_modules/sqlite3"),{parse}=require("/usr/local/lib/node_modules/n8n/node_modules/flatted");
const APPLY=process.argv.includes("--apply"),CREDENTIAL=process.argv.find((arg)=>arg.startsWith("--credential="))?.slice(13)||"/tmp/gs-6944.json",OUTPUT=process.argv.find((arg)=>arg.startsWith("--output="))?.slice(9)||"/tmp/reconcile-6944-clip1.json";
const SPREADSHEET_ID=process.env.AFFILIATE_TRACKER_SPREADSHEET_ID,BATCH="6944",PHONE="6281910833031",CONVERSATION="wa:6281910833031",INDEX=1,WAMID="wamid.HBgNNjI4MTkxMDgzMzAzMRUCABEYEjJGODY3NEE3QUFFQkU0QzE4RAA=",FILE="2026_06_12_15_06_39_run_191__2026_06_12_15_06_39_run_191_clip_0007_v1_b_roll_hook_broll_score9_COBA_STEP_UNTUK_CERAH.mp4",KEY=`${CONVERSATION}:${BATCH}:${FILE}`;
const HEADERS=["whatsapp_message_id","recipient_number","message_type","template_name","source_workflow","source_reference","api_status","accepted_at","current_status","status_timestamp","conversation_json","pricing_json","errors_json","error_code","error_title","error_message","error_details","processed_statuses","status_history_json","updated_at","direction","message_payload_json","send_state","delivery_state"];
const text=(v)=>v==null?"":String(v).trim(),assert=(c,m)=>{if(!c)throw new Error(m);};
function table(values){const headers=(values?.[0]||[]).map(text);return{headers,rows:(values||[]).slice(1).map((row,index)=>({row_number:index+2,...Object.fromEntries(headers.map((name,column)=>[name,text(row[column])]))})).filter((row)=>headers.some((name)=>row[name]))};}
async function token(){const exported=JSON.parse(fs.readFileSync(CREDENTIAL,"utf8")),data=exported?.[0]?.data||{},oauth=typeof data.oauthTokenData==="string"?JSON.parse(data.oauthTokenData):data.oauthTokenData;const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:data.clientId,client_secret:data.clientSecret,refresh_token:oauth.refresh_token,grant_type:"refresh_token"})});const body=await response.json();assert(response.ok&&body.access_token,"oauth_refresh_failed");return body.access_token;}
async function google(url,accessToken,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${accessToken}`,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`google_${response.status}:${body.slice(0,500)}`);return body?JSON.parse(body):{};}
async function sheets(accessToken){const ranges=["WhatsApp Leads!A:AF","Delivery Log!A:R","WhatsApp Message Log!A:X"],query=ranges.map((r)=>`ranges=${encodeURIComponent(r)}`).join("&"),body=await google(`https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}/values:batchGet?${query}&majorDimension=ROWS`,accessToken);return Object.fromEntries(ranges.map((range,index)=>[range.split("!")[0],table(body.valueRanges?.[index]?.values||[])]));}
const all=(db,sql,params=[])=>new Promise((resolve,reject)=>db.all(sql,params,(error,rows)=>error?reject(error):resolve(rows)));
async function evidence(){const db=new sqlite3.Database("/home/node/.n8n/database.sqlite",sqlite3.OPEN_READONLY);try{const rows=await all(db,`select e.id,e."workflowId",e.status,e."startedAt",d.data from execution_entity e join execution_data d on d."executionId"=e.id where d.data like ? order by cast(e.id as integer)`,[`%${WAMID}%`]);let sends=0;const callbacks=[];for(const row of rows){const run=parse(row.data)?.resultData?.runData||{};for(const entry of run["Parse Video Send"]||[])for(const branch of entry?.data?.main||[])for(const item of branch||[]){const value=item.json||{};if(value.delivery_key===KEY&&value.whatsapp_message_id===WAMID&&value.send_success===true)sends++;}for(const entry of run["Verify and Parse WhatsApp Webhook"]||[])for(const branch of entry?.data?.main||[])for(const item of branch||[]){const value=item.json||{};if(value.event_kind==="status"&&value.whatsapp_message_id===WAMID){const epoch=Number(value.whatsapp_timestamp||0);callbacks.push({execution_id:String(row.id),status:text(value.delivery_status||value.raw_event?.status).toLowerCase(),timestamp:epoch?new Date(epoch*1000).toISOString():text(row.startedAt).replace(" ","T")+"Z"});}}}return{sends,callbacks};}finally{db.close();}}
function verify(tables,proof){const delivery=tables["Delivery Log"].rows.filter((row)=>row.batch_number===BATCH&&row.conversation_id===CONVERSATION),row=delivery.find((item)=>Number(item.file_index)===INDEX),messages=tables["WhatsApp Message Log"].rows.filter((item)=>item.whatsapp_message_id===WAMID||item.source_reference===KEY);assert(delivery.length===15,"delivery_clip_count_changed");assert(row&&row.delivery_key===KEY&&row.whatsapp_message_id===WAMID&&["accepted","sent","delivered","read"].includes(text(row.send_state||row.state).toLowerCase())&&Number(row.attempts)===1,"clip1_not_exactly_durable");assert(delivery.filter((item)=>item.whatsapp_message_id===WAMID).length===1,"clip1_duplicate_delivery_wamid");assert(proof.sends===1,"clip1_meta_send_evidence_not_unique");assert(["sent","delivered","read"].every((status)=>proof.callbacks.some((item)=>item.status===status)),"clip1_callback_chain_incomplete");assert(messages.every((item)=>item.whatsapp_message_id===WAMID&&item.source_reference===KEY),"clip1_message_log_conflict");assert(messages.length<=1,"clip1_duplicate_message_log");assert(!delivery.some((item)=>text(item.send_state||item.state).toLowerCase()==="outcome_uncertain"),"6944_uncertain_exists");return{row,messages,delivery};}
(async()=>{assert(SPREADSHEET_ID,"spreadsheet_id_missing");const accessToken=await token(),proof=await evidence(),before=verify(await sheets(accessToken),proof),history=proof.callbacks.sort((a,b)=>a.timestamp.localeCompare(b.timestamp)),latest=history.at(-1),values={whatsapp_message_id:WAMID,recipient_number:PHONE,message_type:"video",template_name:"",source_workflow:"AffWaDelivery2026",source_reference:KEY,api_status:"accepted",accepted_at:before.row.sent_at,current_status:latest.status,status_timestamp:latest.timestamp,conversation_json:"{}",pricing_json:"{}",errors_json:"[]",error_code:"",error_title:"",error_message:"",error_details:"",processed_statuses:JSON.stringify([...new Set(history.map((item)=>item.status))]),status_history_json:JSON.stringify(history),updated_at:latest.timestamp,direction:"outbound",message_payload_json:JSON.stringify({type:"video",source_reference:KEY,batch_number:BATCH,file_index:INDEX,file_name:FILE,reconciled_from_execution:25791}),send_state:"accepted",delivery_state:"delivery_in_progress"},appendRequired=before.messages.length===0;
 if(APPLY&&appendRequired)await google(`https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}/values/${encodeURIComponent("WhatsApp Message Log!A:X")}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,accessToken,{method:"POST",body:JSON.stringify({majorDimension:"ROWS",values:[HEADERS.map((name)=>text(values[name]))]})});
 const after=verify(await sheets(accessToken),proof),remaining=after.delivery.filter((item)=>!item.whatsapp_message_id).map((item)=>Number(item.file_index)).sort((a,b)=>a-b),report={mode:APPLY?"applied":"dry_run",captured_at:new Date().toISOString(),planned_message_append:appendRequired,delivery_row_changed:false,clip1:{row_number:after.row.row_number,wamid:after.row.whatsapp_message_id,attempts:Number(after.row.attempts),state:after.row.send_state||after.row.state,matching_meta_sends:proof.sends,callbacks:history},message_log_rows:after.messages.length,distinct_wamids:new Set(after.delivery.map((item)=>item.whatsapp_message_id).filter(Boolean)).size,outcome_uncertain:after.delivery.filter((item)=>text(item.send_state||item.state).toLowerCase()==="outcome_uncertain").map((item)=>Number(item.file_index)),remaining_indexes:remaining};if(APPLY){assert(after.messages.length===1,"message_log_reconciliation_failed");assert(JSON.stringify(remaining)===JSON.stringify(Array.from({length:14},(_,i)=>i+2)),"remaining_not_2_through_15");}fs.writeFileSync(OUTPUT,JSON.stringify(report,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(report,null,2)+"\n");})().catch((error)=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1;});
