"use strict";
const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, ".."); const API = "http://localhost:5678/api/v1";
const values = {}; for (const line of fs.readFileSync(path.join(ROOT, ".env"), "utf8").split(/\r?\n/)) { const match=line.match(/^([^#=]+)=(.*)$/); if(match) values[match[1].trim()]=match[2]; }
async function api(pathname, options={}) { const response=await fetch(API+pathname,{...options,headers:{"X-N8N-API-KEY":values.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}}); const body=await response.text(); if(!response.ok) throw new Error(`API ${response.status}: ${body.slice(0,500)}`); return body?JSON.parse(body):{}; }
async function main() {
  const uploadReadyArgument = process.argv.find((argument) => argument.startsWith("--mark-upload-ready="));
  const markUploadReadyBatch = uploadReadyArgument ? uploadReadyArgument.slice("--mark-upload-ready=".length) : (process.argv.includes("--mark-upload-ready-6902") ? "6902" : "");
  if (markUploadReadyBatch && !["6901","6902","6903","6904","6905","6906","6907"].includes(markUploadReadyBatch)) throw new Error("upload-ready batch is not allowlisted");
  const reconcileMessageLog = process.argv.includes("--from-message-log");
  const uncertainArgument = process.argv.find((argument) => argument.startsWith("--mark-outcome-uncertain="));
  const uncertainBatch = uncertainArgument ? uncertainArgument.slice("--mark-outcome-uncertain=".length) : "";
  if (uncertainBatch && !["6901","6902","6903","6904","6905","6906","6907"].includes(uncertainBatch)) throw new Error("uncertain batch is not allowlisted");
  const executionArgument = process.argv.find((argument) => argument.startsWith("--from-execution="));
  const executionReconciliations = {
    "14072": { batch_number: "6905", delivery_key: "wa:6282329499945:6905:2026_05_30_12_13_26_run_191__2026_05_30_12_13_26_run_191_clip_0001_v3_black_bars_score9_BIAR_KULIT_TAMPAK_FRESH.mp4", media_id: "2410153246139279", whatsapp_message_id: "wamid.HBgNNjI4MjMyOTQ5OTk0NRUCABEYEjIzNEI3RjY4NUJGNEI5QTUxMgA=" }
  };
  const executionId = executionArgument ? executionArgument.slice("--from-execution=".length) : "";
  const executionReconciliation = executionId ? executionReconciliations[executionId] : null;
  if (executionId && !executionReconciliation) throw new Error("execution reconciliation is not allowlisted");
  const reference=await api("/workflows/AffWaDelivery2026"); const credential=reference.nodes.map((node)=>node.credentials?.googleSheetsOAuth2Api).find(Boolean); if(!credential?.id) throw new Error("Sheets credential missing");
  const pathName=`reconcile-delivery-claims-${crypto.randomUUID()}`;
  const code=String.raw`
function text(v){return v==null?"":String(v).trim();} function records(values){const headers=(values[0]||[]).map(text);return {headers,rows:values.slice(1).map((row,index)=>({row_number:index+2,...Object.fromEntries(headers.map((name,column)=>[name,text(row[column])]))}))};}
const delivery=records($("Read Delivery Log").first().json.values||[]); const headers=delivery.headers; const rows=delivery.rows; const messages=records($json.values||[]).rows;
const affected=new Set(["6901","6902","6903","6904","6905","6906","6907"]); const updates=[]; const reconciled=[];
for(const claim of rows.filter((row)=>affected.has(row.batch_number)&&row.send_state==="send_prepared")) { const sent=rows.find((row)=>row.delivery_key===claim.delivery_key&&row.row_number!==claim.row_number&&row.whatsapp_message_id); if(!sent) continue; const record={...claim,state:"claim_reconciled",send_state:"claim_reconciled",delivery_state:"",last_error:"claim_reconciled_to_row:"+sent.row_number,updated_at:new Date().toISOString()}; updates.push({range:"Delivery Log!A"+claim.row_number+":R"+claim.row_number,majorDimension:"ROWS",values:[headers.map((name)=>text(record[name]))]}); reconciled.push({batch_number:claim.batch_number,delivery_key:claim.delivery_key,claim_row:claim.row_number,sent_row:sent.row_number}); }
if(${markUploadReadyBatch ? "true" : "false"}) { for(const claim of rows.filter((row)=>row.batch_number===${JSON.stringify(markUploadReadyBatch)}&&row.send_state==="send_prepared"&&row.media_id&&!row.whatsapp_message_id)) { const sent=rows.find((row)=>row.delivery_key===claim.delivery_key&&row.row_number!==claim.row_number&&row.whatsapp_message_id); const message=messages.find((row)=>row.source_reference===claim.delivery_key&&row.whatsapp_message_id); if(sent||message) continue; const record={...claim,state:"upload_ready_no_message",send_state:"upload_ready_no_message",last_error:"stopped_before_video_message",updated_at:new Date().toISOString()}; updates.push({range:"Delivery Log!A"+claim.row_number+":R"+claim.row_number,majorDimension:"ROWS",values:[headers.map((name)=>text(record[name]))]}); reconciled.push({batch_number:claim.batch_number,delivery_key:claim.delivery_key,claim_row:claim.row_number,sent_row:"",action:"mark_upload_ready_no_message"}); } }
if(${reconcileMessageLog ? "true" : "false"}) { for(const claim of rows.filter((row)=>row.batch_number==="6902"&&!row.whatsapp_message_id&&["send_prepared","upload_ready_no_message"].includes(row.send_state))) { const message=messages.find((row)=>row.direction==="outbound"&&row.message_type==="video"&&row.source_reference===claim.delivery_key&&row.whatsapp_message_id); if(!message) continue; const status=["accepted","sent","delivered","read","failed"].includes(message.current_status)?message.current_status:(["accepted","sent","delivered","read","failed"].includes(message.send_state)?message.send_state:"accepted"); const now=new Date().toISOString(); const record={...claim,whatsapp_message_id:message.whatsapp_message_id,state:status,send_state:status,delivery_state:["sent","delivered","read","failed"].includes(status)?status:"",sent_at:claim.sent_at||message.sent_at||message.created_at||now,delivered_at:["delivered","read"].includes(status)?(message.delivered_at||message.updated_at||now):claim.delivered_at,last_error:"reconciled_from_message_log_row:"+message.row_number+":execution_13443",updated_at:now}; updates.push({range:"Delivery Log!A"+claim.row_number+":R"+claim.row_number,majorDimension:"ROWS",values:[headers.map((name)=>text(record[name]))]}); reconciled.push({batch_number:claim.batch_number,delivery_key:claim.delivery_key,claim_row:claim.row_number,message_row:message.row_number,action:"reconcile_from_message_log",status}); } }
if(${executionReconciliation ? JSON.stringify(executionReconciliation) : "null"}) { const evidence=${executionReconciliation ? JSON.stringify(executionReconciliation) : "null"}; const claim=rows.find((row)=>row.batch_number===evidence.batch_number&&row.delivery_key===evidence.delivery_key&&!row.whatsapp_message_id&&row.media_id===evidence.media_id&&row.send_state==="send_prepared"); const conflicting=rows.find((row)=>row.whatsapp_message_id===evidence.whatsapp_message_id||row.delivery_key===evidence.delivery_key&&row.whatsapp_message_id); if(!claim) throw new Error("execution_reconciliation_claim_missing_or_changed"); if(conflicting) throw new Error("execution_reconciliation_conflict"); const now=new Date().toISOString(); const record={...claim,whatsapp_message_id:evidence.whatsapp_message_id,state:"accepted",send_state:"accepted",delivery_state:"",sent_at:claim.sent_at||now,last_error:"reconciled_from_execution_${executionId}",updated_at:now}; updates.push({range:"Delivery Log!A"+claim.row_number+":R"+claim.row_number,majorDimension:"ROWS",values:[headers.map((name)=>text(record[name]))]}); reconciled.push({batch_number:claim.batch_number,delivery_key:claim.delivery_key,claim_row:claim.row_number,action:"reconcile_from_execution",status:"accepted",execution_id:"${executionId}"}); }
if(${uncertainBatch ? "true" : "false"}) { for(const claim of rows.filter((row)=>row.batch_number===${JSON.stringify(uncertainBatch)}&&row.send_state==="send_prepared"&&!row.whatsapp_message_id)) { const sent=rows.find((row)=>row.delivery_key===claim.delivery_key&&row.row_number!==claim.row_number&&row.whatsapp_message_id); const message=messages.find((row)=>row.source_reference===claim.delivery_key&&row.whatsapp_message_id); if(sent||message) continue; const record={...claim,state:"outcome_uncertain",send_state:"outcome_uncertain",last_error:"monitor_timeout_execution_14191_no_execution_evidence",updated_at:new Date().toISOString()}; updates.push({range:"Delivery Log!A"+claim.row_number+":R"+claim.row_number,majorDimension:"ROWS",values:[headers.map((name)=>text(record[name]))]}); reconciled.push({batch_number:claim.batch_number,delivery_key:claim.delivery_key,claim_row:claim.row_number,action:"mark_outcome_uncertain"}); } }
return [{json:{updates,reconciled,write_required:updates.length>0}}];`;
  const workflow=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Temporary Reconcile Delivery Claims",nodes:[
    {parameters:{httpMethod:"POST",path:pathName,responseMode:"lastNode",options:{}},id:crypto.randomUUID(),name:"Reconcile Request",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-400,0],webhookId:crypto.randomUUID()},
    {parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${values.AFFILIATE_TRACKER_SPREADSHEET_ID}/values/Delivery%20Log!A:R`,options:{}},id:crypto.randomUUID(),name:"Read Delivery Log",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[-180,0],credentials:{googleSheetsOAuth2Api:credential}},
    {parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${values.AFFILIATE_TRACKER_SPREADSHEET_ID}/values/WhatsApp%20Message%20Log!A:X`,options:{}},id:crypto.randomUUID(),name:"Read Message Log",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[0,0],credentials:{googleSheetsOAuth2Api:credential}},
    {parameters:{jsCode:code},id:crypto.randomUUID(),name:"Prepare Exact Claim Reconciliation",type:"n8n-nodes-base.code",typeVersion:2,position:[180,0]},
    {parameters:{method:"POST",url:`https://sheets.googleapis.com/v4/spreadsheets/${values.AFFILIATE_TRACKER_SPREADSHEET_ID}/values:batchUpdate`,authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",sendBody:true,specifyBody:"json",jsonBody:'={{ JSON.stringify({ valueInputOption: "RAW", data: $json.updates }) }}',options:{}},id:crypto.randomUUID(),name:"Write Reconciled Claim Rows",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[260,0],credentials:{googleSheetsOAuth2Api:credential}},
    {parameters:{jsCode:'const source=$("Prepare Exact Claim Reconciliation").first().json; return [{json:{reconciled:source.reconciled,count:source.reconciled.length}}];'},id:crypto.randomUUID(),name:"Reconciliation Result",type:"n8n-nodes-base.code",typeVersion:2,position:[480,0]}
  ],connections:{"Reconcile Request":{main:[[{node:"Read Delivery Log",type:"main",index:0}]]},"Read Delivery Log":{main:[[{node:"Read Message Log",type:"main",index:0}]]},"Read Message Log":{main:[[{node:"Prepare Exact Claim Reconciliation",type:"main",index:0}]]},"Prepare Exact Claim Reconciliation":{main:[[{node:"Write Reconciled Claim Rows",type:"main",index:0}]]},"Write Reconciled Claim Rows":{main:[[{node:"Reconciliation Result",type:"main",index:0}]]}},settings:{executionOrder:"v1",saveDataSuccessExecution:"none",saveDataErrorExecution:"all"}})});
  try { await api(`/workflows/${workflow.id}/activate`,{method:"POST"}); const response=await fetch(`http://localhost:5678/webhook/${pathName}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"}); const body=await response.text(); if(!response.ok) throw new Error(`Reconciliation HTTP ${response.status}: ${body.slice(0,500)}`); process.stdout.write(JSON.stringify(JSON.parse(body),null,2)+"\n"); }
  finally { try{await api(`/workflows/${workflow.id}/deactivate`,{method:"POST"});}catch{} await api(`/workflows/${workflow.id}`,{method:"DELETE"}); }
}
main().catch((error)=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1;});
