"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",DEPLOYED=path.join(ROOT,"n8n","exports","fresh-production-incident-6945-6947-20260828","deployment","AffWaDelivery2026.after.json"),SOURCE=fs.existsSync(DEPLOYED)?DEPLOYED:path.join(ROOT,"n8n","exports","fresh-production-incident-6945-6947-20260828","pre-pause","AffWaDelivery2026.json"),OUT=path.join(ROOT,"n8n","exports","fresh-production-incident-6945-6947-20260828","actual-node-controlled-tests.json");
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map(line=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""]}).filter(([key])=>key)),live=JSON.parse(fs.readFileSync(SOURCE,"utf8"));
const id=()=>crypto.randomUUID(),edge=(node,index=0)=>({node,type:"main",index}),clone=(name)=>{const node=structuredClone(live.nodes.find(item=>item.name===name));if(!node)throw new Error(`production_node_missing:${name}`);node.id=id();return node};
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])]));return v}const sourceHash=crypto.createHash("sha256").update(JSON.stringify(stable({name:live.name,nodes:live.nodes,connections:live.connections,settings:live.settings}))).digest("hex");
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}}),body=await response.text();if(!response.ok)throw new Error(`n8n_${response.status}:${route}:${body.slice(0,800)}`);return body?JSON.parse(body):{}}
function code(name,jsCode){return{id:id(),name,type:"n8n-nodes-base.code",typeVersion:2,position:[0,0],parameters:{jsCode}}}
const fixture=String.raw`
const scenario=String($json.body?.scenario||$json.scenario||"fresh"),resumable=scenario==="resumable",batch=resumable?"99002":"99001",phone=resumable?"6200000000002":"6200000000001",conversation="wa:"+phone,username=resumable?"codex_resumable_fixture":"codex_fresh_fixture",now=new Date().toISOString();
const DH=["delivery_key","conversation_id","whatsapp_number","batch_number","file_index","file_name","media_id","whatsapp_message_id","state","attempts","uploaded_at","sent_at","delivered_at","failed_at","last_error","updated_at","send_state","delivery_state"],MH=["whatsapp_message_id","recipient_number","message_type","template_name","source_workflow","source_reference","api_status","accepted_at","current_status","status_timestamp","conversation_json","pricing_json","errors_json","error_code","error_title","error_message","error_details","processed_statuses","status_history_json","updated_at","direction","message_payload_json","send_state","delivery_state"],LH=["username","whatsapp_number","conversation_id","captured_at","reply_1","reply_2","reply_3","state","opt_in_message_id","opt_in_sent_at","opted_in_at","declined_at","batch_number","batch_reserved_at","delivery_started_at","files_expected","files_sent","files_delivered","files_failed","files_sent_at","files_delivered_at","posted_confirmed_at","last_whatsapp_message_id","last_inbound_at","last_intent","last_intent_confidence","last_error","updated_at","wa_id","last_inbound_message_id","window_expires_at","delivery_state"];
const existing=[];for(let i=1;i<=(resumable?5:0);i++){const file="clip-"+String(i).padStart(2,"0")+".mp4",key=conversation+":"+batch+":"+file,mid="wamid.MOCKDURABLE"+String(i).padStart(8,"0");existing.push(DH.map(name=>({delivery_key:key,conversation_id:conversation,whatsapp_number:phone,batch_number:batch,file_index:String(i),file_name:file,media_id:"media.old."+i,whatsapp_message_id:mid,state:"accepted",attempts:"1",uploaded_at:now,sent_at:now,updated_at:now,send_state:"accepted",delivery_state:""})[name]||""))}
return[{json:{scenario,resumable,reservation_ok:true,reservation_won:true,delivery_context_valid:true,assignment_id:conversation+":"+batch,batch_number:batch,conversation_id:conversation,whatsapp_number:phone,wa_id:phone,username,tiktok_username:username,row_number:900,expected_clip_count:15,files_expected:"15",files_sent:String(existing.length),delivery_state:existing.length?"partial":"delivery_in_progress",batch_reserved_at:now,delivery_started_at:now,updated_at:now,lead_headers:LH,delivery_log_values:[DH,...existing],message_log_values:[MH]}}];`;
const pending=String.raw`
const s=$("Restore and Validate Delivery Context").first().json,start=s.resumable?6:1,items=[];for(let i=start;i<=15;i++){const file="clip-"+String(i).padStart(2,"0")+".mp4";items.push({json:{...s,file_index:i,file_name:file,delivery_key:s.conversation_id+":"+s.batch_number+":"+file,attempts:1,delivery_log_row_number:1000+i,media_id:"media.mock."+i,uploaded_at:new Date().toISOString(),resume_position:i-start+1,remaining_clip_count:16-i,zero_remaining_recovery:false}})}return items;`;
const mockGuard=String.raw`const s=$input.first();return[{json:{...s.json,media_id:s.json.media_id||"media.mock."+s.json.file_index,uploaded_at:s.json.uploaded_at||new Date().toISOString()},binary:s.binary}];`;
const mockMeta=String.raw`const s=$("Guard Cached Clip Send").item.json;return[{json:{messages:[{id:"wamid.MOCKSEND"+String(s.file_index).padStart(8,"0"),message_status:"accepted"}]}}];`;
const mockPrior=String.raw`const s=$("Prepare In-Flight Send Claim").item.json;return[{json:{values:[s.in_flight_row_values]}}];`;
const mockReadback=String.raw`const s=$("Validate Immediate Successful Send").item.json,target=$json.successful_clip_readback_url,expected="Delivery%20Log!A"+s.delivery_log_row_number+"%3AR"+s.delivery_log_row_number;if(!target.endsWith(expected))throw new Error("controlled_exact_readback_target_failed");return[{json:{values:[s.delivery_row_values],mock_target:target}}];`;
const nodes=[
 {id:id(),name:"Controlled Fresh Path Request",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[0,0],webhookId:id(),parameters:{httpMethod:"POST",path:`controlled-fresh-path-${id()}`,responseMode:"lastNode",options:{}}},
 code("Restore and Validate Delivery Context",fixture),clone("Prepare Assignment Start Log"),code("Log Assignment Start (Nonblocking)",`const s=$json;if(s.phase!=="start")throw new Error("controlled_start_logger_missing");return[{json:{start_logger_reached:true,start:s}}];`),code("Prepare Resumable Delivery Items",pending),clone("Loop Through Files"),clone("Prepare In-Flight Send Claim"),code("Mock Persist and Verify In-Flight Claim",`const s=$input.first();if(s.json.in_flight_row_values?.[16]!=="outcome_uncertain")throw new Error("controlled_uncertain_claim_missing");return[s];`),code("Guard Cached Clip Send",mockGuard),code("Mock Meta Video Send",mockMeta),clone("Parse Video Send"),code("Read Delivery Row after Meta Success",mockPrior),clone("Validate Immediate Successful Send"),clone("IF Successful Send Persistence Required"),code("Persist Successful Clip Immediately",`return[{json:{spreadsheetId:"mock",updatedRange:"Delivery Log!A"+$('Validate Immediate Successful Send').item.json.delivery_log_row_number+":R"+$('Validate Immediate Successful Send').item.json.delivery_log_row_number,updatedRows:1}}];`),clone("Prepare Successful Clip Read-Back Target"),code("Read Back Persisted Successful Clip",mockReadback),clone("Confirm Successful Clip Durable"),code("Wait Between Recipient Messages",`return $input.all();`),clone("Prepare Batched Delivery Tracking"),code("Batch Write Delivery Results",`return[{json:{updatedRows:$json.delivery_updates.length}}];`),clone("Capture Delivery Batch Write Result"),clone("IF Batched Messages Exist"),code("Append Message Results Batch",`return[{json:{updates:{updatedRows:$json.message_rows.length}}}];`),clone("Capture Message Batch Write Result"),clone("Prepare Durable Queue Status"),clone("Prepare Cached Delivery Summary"),code("Update Final Send State",`const s=$input.first().json;if(s.files_sent!=="15"||s.delivery_state!=="files_sent")throw new Error("controlled_aggregate_finalization_failed");return[{json:{...s,lead_finalization_reached:true}}];`),clone("Done: Delivery Send Attempt"),clone("Prepare Assignment Final Log"),code("Log Assignment Final (Nonblocking)",`const s=$input.first().json,batch=$('Prepare Batched Delivery Tracking').first().json,results=batch.results||[],durable=results.filter(r=>r.immediate_persistence_verified&&r.send_success&&r.whatsapp_message_id).length;if(s.phase!=="final"||s.status!=="Complete"||Number(s.clips_sent_count)!==15||durable!==results.length)throw new Error("controlled_final_logger_payload_invalid");return[{json:{scenario:$('Restore and Validate Delivery Context').first().json.scenario,start_logger_reached:true,uncertain_claims:results.length,meta_successes:results.filter(r=>r.send_success).length,durable_confirmations:durable,aggregate_items:results.length,lead_finalization_reached:true,final_logger_reached:true,final:s}}];`)
];
const by=Object.fromEntries(nodes.map(n=>[n.name,n]));
const c={};const link=(a,b,branch=0)=>{c[a]||={main:[]};while(c[a].main.length<=branch)c[a].main.push([]);c[a].main[branch].push(edge(b))};
link("Controlled Fresh Path Request","Restore and Validate Delivery Context");link("Restore and Validate Delivery Context","Prepare Assignment Start Log");link("Prepare Assignment Start Log","Log Assignment Start (Nonblocking)");link("Log Assignment Start (Nonblocking)","Prepare Resumable Delivery Items");link("Prepare Resumable Delivery Items","Loop Through Files");
link("Loop Through Files","Prepare Batched Delivery Tracking",0);link("Loop Through Files","Prepare In-Flight Send Claim",1);link("Prepare In-Flight Send Claim","Mock Persist and Verify In-Flight Claim");link("Mock Persist and Verify In-Flight Claim","Guard Cached Clip Send");link("Guard Cached Clip Send","Mock Meta Video Send");link("Mock Meta Video Send","Parse Video Send");link("Parse Video Send","Read Delivery Row after Meta Success");link("Read Delivery Row after Meta Success","Validate Immediate Successful Send");link("Validate Immediate Successful Send","IF Successful Send Persistence Required");link("IF Successful Send Persistence Required","Persist Successful Clip Immediately",0);link("Persist Successful Clip Immediately","Prepare Successful Clip Read-Back Target");link("Prepare Successful Clip Read-Back Target","Read Back Persisted Successful Clip");link("Read Back Persisted Successful Clip","Confirm Successful Clip Durable");link("Confirm Successful Clip Durable","Wait Between Recipient Messages");link("Wait Between Recipient Messages","Loop Through Files");
link("Prepare Batched Delivery Tracking","Batch Write Delivery Results");link("Batch Write Delivery Results","Capture Delivery Batch Write Result");link("Capture Delivery Batch Write Result","IF Batched Messages Exist");link("IF Batched Messages Exist","Append Message Results Batch",0);link("Append Message Results Batch","Capture Message Batch Write Result");link("Capture Message Batch Write Result","Prepare Durable Queue Status");link("Prepare Durable Queue Status","Prepare Cached Delivery Summary");link("Prepare Cached Delivery Summary","Update Final Send State");link("Update Final Send State","Done: Delivery Send Attempt");link("Done: Delivery Send Attempt","Prepare Assignment Final Log");link("Prepare Assignment Final Log","Log Assignment Final (Nonblocking)");
(async()=>{const route=by["Controlled Fresh Path Request"].parameters.path,workflow=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Controlled Actual-Node Fresh Delivery Graph 20260828",nodes,connections:c,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all"}})}),tests=[];try{await api(`/workflows/${workflow.id}/activate`,{method:"POST"});for(const scenario of ["fresh","resumable"]){const response=await fetch(`http://localhost:5678/webhook/${route}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario})}),body=await response.text();let result;try{result=JSON.parse(body)}catch{result={raw:body}}const expected=scenario==="fresh"?15:10,passed=response.ok&&result.final_logger_reached===true&&result.uncertain_claims===expected&&result.meta_successes===expected&&result.durable_confirmations===expected&&result.aggregate_items===expected&&result.final?.clips_sent_count===15;tests.push({scenario,http_status:response.status,expected_new_clips:expected,result,passed});if(!passed)throw new Error(`controlled_${scenario}_failed:${body.slice(0,1000)}`)}const report={captured_at:new Date().toISOString(),workflow_id:workflow.id,production_source_version:live.versionId,production_source_hash:sourceHash,real_meta_requests:0,real_google_writes:0,exact_production_nodes:["Prepare Assignment Start Log","Loop Through Files","Prepare In-Flight Send Claim","Parse Video Send","Validate Immediate Successful Send","IF Successful Send Persistence Required","Prepare Successful Clip Read-Back Target","Confirm Successful Clip Durable","Prepare Batched Delivery Tracking","Capture Delivery Batch Write Result","IF Batched Messages Exist","Capture Message Batch Write Result","Prepare Durable Queue Status","Prepare Cached Delivery Summary","Done: Delivery Send Attempt","Prepare Assignment Final Log"],tests};fs.writeFileSync(OUT,JSON.stringify(report,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(report,null,2)+"\n")}finally{try{await api(`/workflows/${workflow.id}/deactivate`,{method:"POST"})}catch{}try{await api(`/workflows/${workflow.id}`,{method:"DELETE"})}catch{}}})().catch(error=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1});
