"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),{spawnSync}=require("node:child_process");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",OUT=path.join(ROOT,"n8n","exports","assignment-6944-readback-recovery-20260824","controlled-test-executions.json");
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map((line)=>{const i=line.indexOf("=");return i>0?[line.slice(0,i).trim(),line.slice(i+1)]:["",""];}).filter(([key])=>key));
const immediateCode=fs.readFileSync(path.join(ROOT,"n8n","code","validate-immediate-successful-send.js"),"utf8"),prepareCode=fs.readFileSync(path.join(ROOT,"n8n","code","prepare-successful-clip-readback-target.js"),"utf8"),confirmCode=fs.readFileSync(path.join(ROOT,"n8n","code","confirm-successful-clip-durable.js"),"utf8");
const id=()=>crypto.randomUUID(),edge=(node)=>({main:[[{node,type:"main",index:0}]]});
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`n8n_${response.status}:${route}:${body.slice(0,500)}`);return body?JSON.parse(body):{};}
function latest(workflowId){const script=`const sqlite3=require('/usr/local/lib/node_modules/n8n/node_modules/sqlite3');const{parse}=require('/usr/local/lib/node_modules/n8n/node_modules/flatted');const db=new sqlite3.Database('/home/node/.n8n/database.sqlite',sqlite3.OPEN_READONLY);db.get('select e.id,e.status,d.data from execution_entity e join execution_data d on d."executionId"=e.id where e."workflowId"=? order by cast(e.id as integer) desc limit 1',[${JSON.stringify(workflowId)}],(error,row)=>{if(error)throw error;const data=parse(row.data),run=data?.resultData?.runData||{},failure=data?.resultData?.error||{},out=(run['Mock Aggregate and Final Logger']?.[0]?.data?.main?.[0]||[]).map(x=>x.json),prep=(run['Prepare Successful Clip Read-Back Target']?.[0]?.data?.main?.[0]||[]).map(x=>x.json),valid=(run['Validate Immediate Successful Send']?.[0]?.data?.main?.[0]||[]).map(x=>x.json);console.log(JSON.stringify({id:String(row.id),status:row.status,error:[failure.message,failure.description,failure.stack].filter(Boolean).join(' | '),errorNode:failure.node?.name||'',output:out[0]||null,prepared:prep[0]||null,validated:valid[0]||null}));db.close();});`;const result=spawnSync("docker",["exec","-u","node","n8n-local","node","-e",script],{cwd:ROOT,encoding:"utf8",timeout:30000});if(result.status!==0)throw new Error(result.stderr||result.stdout);return JSON.parse(result.stdout.trim().split(/\r?\n/).at(-1));}
const sourceCode=String.raw`
const scenario=String($env.READBACK_TEST_SCENARIO||"A");
const source={scenario,send_success:true,whatsapp_message_id:"wamid.MOCKREADBACK000001",delivery_key:"wa:6200000000000:9000:clip-01.mp4",conversation_id:"wa:6200000000000",whatsapp_number:"6200000000000",batch_number:"9000",file_index:1,file_name:"clip-01.mp4",attempts:2,delivery_log_row_number:101,message_log_values:[["whatsapp_message_id","recipient_number","message_type","template_name","source_workflow","source_reference","api_status","accepted_at","current_status","status_timestamp","conversation_json","pricing_json","errors_json","error_code","error_title","error_message","error_details","processed_statuses","status_history_json","updated_at","direction"]]};
if(scenario==="D_blank")source.delivery_log_row_number="";if(scenario==="E_zero")source.delivery_log_row_number=0;if(scenario==="E_negative")source.delivery_log_row_number=-1;if(scenario==="E_text")source.delivery_log_row_number="abc";
const row=[source.delivery_key,source.conversation_id,source.whatsapp_number,source.batch_number,"1",source.file_name,"media.mock","","outcome_uncertain","2","2026-08-24T00:00:00.000Z","","","","","2026-08-24T00:00:01.000Z","outcome_uncertain",""];
if(scenario==="C_17")row.pop();if(scenario==="G_replay"){row[7]=source.whatsapp_message_id;row[8]="accepted";row[16]="accepted";}if(scenario==="H_conflict")row[7]="wamid.MOCKREADBACKCONFLICT99";
source.mock_initial_values=[row];return[{json:source}];`;
const initialRead=`return [{json:{values:$("Parse Video Send").item.json.mock_initial_values}}];`;
const mockPut=`return [{json:{spreadsheetId:"mock",updatedRange:"'Delivery Log'!A101:R101",updatedRows:1}}];`;
const mockRead=String.raw`
const source=$("Validate Immediate Successful Send").item.json,row=[source.delivery_key,source.conversation_id,source.whatsapp_number,source.batch_number,String(source.file_index),source.file_name,"media.mock",source.whatsapp_message_id,"accepted",String(source.attempts),"2026-08-24T00:00:00.000Z","2026-08-24T00:00:02.000Z","","","","2026-08-24T00:00:02.000Z","accepted",""];
if(source.scenario==="C_17")row.pop();if(source.scenario==="F_wrong_row")row[0]="wa:6200000000000:9001:other.mp4";
const expected=`+"`Delivery%20Log!A${source.delivery_log_row_number}%3AR${source.delivery_log_row_number}`"+`;if(!$json.successful_clip_readback_url.endsWith(expected))throw new Error("mock_readback_not_exact_one_row");return[{json:{values:[row],mock_requested_url:$json.successful_clip_readback_url}}];`;
const aggregate=String.raw`
const item=$json,scenario=String(item.scenario||""),count=scenario==="I_two"?2:scenario==="J_fifteen"?15:1,rows=[];for(let index=1;index<=count;index++){const row=100+index,url="https://sheets.googleapis.com/v4/spreadsheets/mock/values/Delivery%20Log!A"+row+"%3AR"+row;rows.push({index,row,url,durable:true});}for(let i=0;i<rows.length;i++){if(i>0&&!rows[i-1].durable)throw new Error("mock_loop_advanced_before_durable");if(!rows[i].url.endsWith("A"+rows[i].row+"%3AR"+rows[i].row))throw new Error("mock_loop_wrong_exact_row");}const distinct=new Set(rows.map(x=>x.url));if(distinct.size!==count)throw new Error("mock_loop_duplicate_target");return[{json:{scenario,immediate_persistence_verified:item.immediate_persistence_verified,items_durable:count,aggregate_items:count,final_logger_items:1,exact_targets:count,unique_durable_wamids:count,loop_order_verified:true}}];`;
(async()=>{
 const nodes=[
  {id:id(),name:"Controlled Trigger",type:"n8n-nodes-base.manualTrigger",typeVersion:1,position:[0,0],parameters:{}},
  {id:id(),name:"Parse Video Send",type:"n8n-nodes-base.code",typeVersion:2,position:[220,0],parameters:{jsCode:sourceCode}},
  {id:id(),name:"Mock Initial Delivery Read",type:"n8n-nodes-base.code",typeVersion:2,position:[440,0],parameters:{jsCode:initialRead}},
  {id:id(),name:"Validate Immediate Successful Send",type:"n8n-nodes-base.code",typeVersion:2,position:[660,0],parameters:{jsCode:immediateCode}},
  {id:id(),name:"Mock Successful PUT Losing Input Context",type:"n8n-nodes-base.code",typeVersion:2,position:[880,0],parameters:{jsCode:mockPut}},
  {id:id(),name:"Prepare Successful Clip Read-Back Target",type:"n8n-nodes-base.code",typeVersion:2,position:[1100,0],parameters:{jsCode:prepareCode}},
  {id:id(),name:"Mock Exact One-Row Google Read",type:"n8n-nodes-base.code",typeVersion:2,position:[1320,0],parameters:{jsCode:mockRead}},
  {id:id(),name:"Confirm Successful Clip Durable",type:"n8n-nodes-base.code",typeVersion:2,position:[1540,0],parameters:{jsCode:confirmCode}},
  {id:id(),name:"Mock Aggregate and Final Logger",type:"n8n-nodes-base.code",typeVersion:2,position:[1760,0],parameters:{jsCode:aggregate}},
 ];
 const names=nodes.map(n=>n.name),connections=Object.fromEntries(names.slice(0,-1).map((name,index)=>[name,edge(names[index+1])]));
 const workflow=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Controlled Mock - Immediate Readback Context 20260824",nodes,connections,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all",saveManualExecutions:true}})});
 const cases=[
  {test:"A",scenario:"A",status:"success"},{test:"B",scenario:"B_exact",status:"success"},{test:"C",scenario:"C_17",status:"success"},
  {test:"D",scenario:"D_blank",status:"error",error:"successful_clip_readback_row_number_invalid"},{test:"E-zero",scenario:"E_zero",status:"error",error:"successful_clip_readback_row_number_invalid"},{test:"E-negative",scenario:"E_negative",status:"error",error:"successful_clip_readback_row_number_invalid"},{test:"E-text",scenario:"E_text",status:"error",error:"successful_clip_readback_row_number_invalid"},
  {test:"F",scenario:"F_wrong_row",status:"error",error:"successful_clip_persistence_not_verified"},{test:"G",scenario:"G_replay",status:"success",replay:true},{test:"H",scenario:"H_conflict",status:"error",error:"successful_message_id_conflict"},{test:"I",scenario:"I_two",status:"success",count:2},{test:"J",scenario:"J_fifteen",status:"success",count:15}
 ];
 const executions=[];
 for(let index=0;index<cases.length;index++){const item=cases[index],run=spawnSync("docker",["exec","-u","node","-e",`READBACK_TEST_SCENARIO=${item.scenario}`,"-e",`N8N_RUNNERS_BROKER_PORT=${6100+index}`,"n8n-local","n8n","execute",`--id=${workflow.id}`,"--rawOutput"],{cwd:ROOT,encoding:"utf8",timeout:120000}),execution=latest(workflow.id);const exact=execution.prepared?.successful_clip_readback_url?.endsWith("Delivery%20Log!A101%3AR101")===true;const passed=execution.status===item.status&&(!item.error||execution.error.includes(item.error))&&(item.status!=="success"||execution.output?.immediate_persistence_verified===true)&&(item.status!=="success"||exact)&&(item.count===undefined||execution.output?.aggregate_items===item.count)&&(item.replay!==true||execution.validated?.immediate_persistence_required===false);executions.push({...item,execution_id:execution.id,actual_status:execution.status,error_node:execution.errorNode,error:execution.error,prepared_url:execution.prepared?.successful_clip_readback_url||"",validated_immediate_required:execution.validated?.immediate_persistence_required,output:execution.output,cli_exit_code:run.status,passed});if(!passed)throw new Error(`controlled_test_failed:${item.test}:${JSON.stringify(execution)}`);}
 const report={captured_at:new Date().toISOString(),workflow_id:workflow.id,workflow_name:workflow.name,active:workflow.active,real_whatsapp_requests:0,meta_or_upload_nodes:0,executions};fs.writeFileSync(OUT,JSON.stringify(report,null,2)+"\n",{mode:0o600});process.stdout.write(JSON.stringify(report,null,2)+"\n");
})().catch((error)=>{process.stderr.write(`${error.stack||error.message}\n`);process.exitCode=1;});
