"use strict";
const crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path");
const ROOT=path.resolve(__dirname,".."),API="http://localhost:5678/api/v1",phone=String(process.argv[2]||"").replace(/\D/g,"");if(!phone)throw new Error("phone required");
const env=Object.fromEntries(fs.readFileSync(path.join(ROOT,".env"),"utf8").split(/\r?\n/).map((line)=>{const i=line.indexOf("=");return i>0?[line.slice(0,i),line.slice(i+1)]:["",""]}).filter(([key])=>key));
const key=env.N8N_API_KEY;if(!key)throw new Error("N8N_API_KEY missing");
const delivery=JSON.parse(fs.readFileSync(path.join(ROOT,"n8n","imports","affiliate-whatsapp-file-delivery.json"),"utf8"));const source=delivery.nodes.find((node)=>node.name==="Read Delivery Log for Resume"),credential=source.credentials.googleSheetsOAuth2Api,spreadsheetId=/spreadsheets\/([^/]+)/.exec(source.parameters.url)[1];
const ranges=["'WhatsApp Leads'!A:AE","'Delivery Log'!A:R","'WhatsApp Message Log'!A:X","'Affiliate Assignments'!A:Z","'Human Queue'!A:R"];const query=new URLSearchParams({majorDimension:"ROWS",valueRenderOption:"UNFORMATTED_VALUE"});for(const range of ranges)query.append("ranges",range);
const id=()=>crypto.randomUUID(),node=(name,type,typeVersion,position,parameters={},extra={})=>({id:id(),name,type,typeVersion,position,parameters,...extra}),name="Temporary Audit - Test Phone Sheet Baseline",webhookPath="codex-phone-audit-"+crypto.randomBytes(8).toString("hex");
const trigger=node("Production Phone Baseline","n8n-nodes-base.webhook",2.1,[-300,0],{httpMethod:"POST",path:webhookPath,responseMode:"lastNode",options:{}},{webhookId:id()});
const read=node("Read Production Test Baseline Once","n8n-nodes-base.httpRequest",4.4,[-60,0],{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values:batchGet?${query}`,options:{}},{credentials:{googleSheetsOAuth2Api:credential}});
const code=`const target=${JSON.stringify(phone)};const digits=(v)=>String(v??"").replace(/\\D/g,"");const result={spreadsheet_id:${JSON.stringify(spreadsheetId)},phone:target,checked_at_utc:new Date().toISOString(),tabs:{}};for(const entry of $json.valueRanges||[]){const title=String(entry.range||"").split("!")[0].replace(/^'|'$/g,"");const values=entry.values||[],headers=(values[0]||[]).map((v)=>String(v??"").trim());const records=values.slice(1).map((row,index)=>({row_number:index+2,...Object.fromEntries(headers.map((h,i)=>[h,row[i]??""]))}));const matches=records.filter((record)=>Object.values(record).some((value)=>digits(value)===target));result.tabs[title]={total_rows:records.length,matches};}return [{json:result}];`;
const summarize=node("Return Phone Baseline","n8n-nodes-base.code",2,[180,0],{jsCode:code});
const desired={name,nodes:[trigger,read,summarize],connections:{[trigger.name]:{main:[[{node:read.name,type:"main",index:0}]]},[read.name]:{main:[[{node:summarize.name,type:"main",index:0}]]}},settings:{executionOrder:"v1",saveDataErrorExecution:"all",saveDataSuccessExecution:"all"}};
async function request(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":key,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`n8n API ${response.status} ${route}: ${body.slice(0,800)}`);return body?JSON.parse(body):null}
async function main(){const list=await request("/workflows?limit=250"),previous=(list.data||[]).find((workflow)=>workflow.name===name);if(previous?.active)await request(`/workflows/${previous.id}/deactivate`,{method:"POST"});const saved=previous?await request(`/workflows/${previous.id}`,{method:"PUT",body:JSON.stringify(desired)}):await request("/workflows",{method:"POST",body:JSON.stringify(desired)});await request(`/workflows/${saved.id}/activate`,{method:"POST"});let status=0,body="";try{const response=await fetch(`http://localhost:5678/webhook/${webhookPath}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});status=response.status;body=await response.text()}finally{await request(`/workflows/${saved.id}/deactivate`,{method:"POST"})}process.stdout.write(JSON.stringify({workflow_id:saved.id,http_status:status,response:body?JSON.parse(body):{}},null,2)+"\n");if(status<200||status>=300)process.exitCode=1}
main().catch((error)=>{process.stderr.write((error.stack||error.message)+"\n");process.exitCode=1});
