"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
const API = "http://localhost:5678/api/v1";
const SHEET = "1eyA1XRNZU0usuii801IrJCJHp8oCh2XjlfROrzzvpwE";
const PHONE = "6281120262823", CONVERSATION = "wa:6281120262823", BATCH = "6916";
const env = Object.fromEntries(fs.readFileSync(path.join(ROOT, ".env"), "utf8").split(/\r?\n/).map((line) => { const i = line.indexOf("="); return i > 0 ? [line.slice(0, i), line.slice(i + 1)] : ["", ""]; }).filter(([key]) => key));
const id = () => crypto.randomUUID(); const edge = (node) => ({ main: [[{ node, type: "main", index: 0 }]] });
async function api(route, options = {}) { const response = await fetch(API + route, { ...options, headers: { "X-N8N-API-KEY": env.N8N_API_KEY, ...(options.body ? { "Content-Type": "application/json" } : {}) } }); const body = await response.text(); if (!response.ok) throw new Error(`n8n API ${response.status} ${route}: ${body.slice(0, 700)}`); return body ? JSON.parse(body) : {}; }

(async () => {
  const delivery = await api("/workflows/AffWaDelivery2026"); const credential = delivery.nodes.map((node) => node.credentials?.googleSheetsOAuth2Api).find(Boolean); if (!credential) throw new Error("credential missing");
  const route = `stale-zero-recovery-${id()}`;
  const trigger = { id: id(), name: "Create Verified Stale State Fixture", type: "n8n-nodes-base.webhook", typeVersion: 2.1, position: [-660, 0], webhookId: id(), parameters: { httpMethod: "POST", path: route, responseMode: "lastNode", options: {} } };
  const read = { id: id(), name: "Read Canonical and Durable Records", type: "n8n-nodes-base.httpRequest", typeVersion: 4.4, position: [-440, 0], credentials: { googleSheetsOAuth2Api: credential }, parameters: { authentication: "predefinedCredentialType", nodeCredentialType: "googleSheetsOAuth2Api", url: `https://sheets.googleapis.com/v4/spreadsheets/${SHEET}/values:batchGet?${["WhatsApp Leads!A:AE", "Delivery Log!A:R", "WhatsApp Message Log!A:X"].map((r) => `ranges=${encodeURIComponent(r)}`).join("&")}`, options: { timeout: 45000 } } };
  const code = `const PHONE=${JSON.stringify(PHONE)},CONV=${JSON.stringify(CONVERSATION)},BATCH=${JSON.stringify(BATCH)},text=v=>v==null?"":String(v).trim(),digits=v=>text(v).replace(/\\D/g,"");function table(v){const h=(v?.[0]||[]).map(text);return{headers:h,rows:(v||[]).slice(1).map((r,i)=>({row_number:i+2,...Object.fromEntries(h.map((n,c)=>[n,text(r[c])]))})).filter(r=>Object.values(r).some(text))}}const ranges=$json.valueRanges||[],leads=table(ranges[0]?.values),delivery=table(ranges[1]?.values),messages=table(ranges[2]?.values),match=leads.rows.filter(r=>r.conversation_id===CONV&&digits(r.wa_id||r.whatsapp_number)===PHONE&&r.batch_number===BATCH);if(match.length!==1)throw new Error("stale_fixture_lead_not_unique");const lead=match[0],detail=delivery.rows.filter(r=>r.conversation_id===CONV&&r.batch_number===BATCH&&digits(r.whatsapp_number)===PHONE),valid=detail.filter(r=>/^wamid\\./.test(r.whatsapp_message_id)&&["accepted","sent","delivered","read"].includes(r.delivery_state||r.state||r.send_state));if(detail.length!==15||new Set(valid.map(r=>r.delivery_key)).size!==15||new Set(valid.map(r=>r.whatsapp_message_id)).size!==15||detail.some(r=>r.last_error))throw new Error("stale_fixture_durable_delivery_precondition_failed");const msg=messages.rows.filter(r=>r.conversation_id===CONV||digits(r.recipient_number||r.whatsapp_number)===PHONE);if(new Set(msg.map(r=>r.whatsapp_message_id||r.message_id).filter(v=>/^wamid\\./.test(v))).size!==15)throw new Error("stale_fixture_message_precondition_failed");if(lead.state!=="files_sent"||lead.files_sent!=="15"||lead.files_failed!=="0")throw new Error("canonical_lead_not_complete_before_fixture");const record={...lead,state:"delivery_in_progress",files_expected:"15",files_sent:"0",files_failed:"0",files_sent_at:"",last_error:"",updated_at:new Date().toISOString()};return[{json:{row_number:lead.row_number,before:{state:lead.state,files_sent:lead.files_sent,files_failed:lead.files_failed},row_values:[leads.headers.map(h=>text(record[h]))],verified_message_ids:15}}];`;
  const prepare = { id: id(), name: "Verify and Build Stale State Only", type: "n8n-nodes-base.code", typeVersion: 2, position: [-220, 0], parameters: { jsCode: code } };
  const write = { id: id(), name: "Write Controlled Stale Canonical State", type: "n8n-nodes-base.httpRequest", typeVersion: 4.4, position: [0, 0], credentials: { googleSheetsOAuth2Api: credential }, parameters: { authentication: "predefinedCredentialType", nodeCredentialType: "googleSheetsOAuth2Api", method: "PUT", url: `=https://sheets.googleapis.com/v4/spreadsheets/${SHEET}/values/WhatsApp%20Leads!A{{$('Verify and Build Stale State Only').first().json.row_number}}%3AAE{{$('Verify and Build Stale State Only').first().json.row_number}}?valueInputOption=RAW`, sendBody: true, specifyBody: "json", jsonBody: "={{ JSON.stringify({majorDimension:'ROWS',values:$('Verify and Build Stale State Only').first().json.row_values}) }}", options: { timeout: 45000 } } };
  const reread = { id: id(), name: "Reread Controlled Stale State", type: "n8n-nodes-base.httpRequest", typeVersion: 4.4, position: [220, 0], credentials: { googleSheetsOAuth2Api: credential }, parameters: { authentication: "predefinedCredentialType", nodeCredentialType: "googleSheetsOAuth2Api", url: `=https://sheets.googleapis.com/v4/spreadsheets/${SHEET}/values/WhatsApp%20Leads!A{{$('Verify and Build Stale State Only').first().json.row_number}}%3AAE{{$('Verify and Build Stale State Only').first().json.row_number}}`, options: { timeout: 45000 } } };
  const verify = { id: id(), name: "Confirm Stale Fixture", type: "n8n-nodes-base.code", typeVersion: 2, position: [440, 0], parameters: { jsCode: `const p=$("Verify and Build Stale State Only").first().json,row=$json.values?.[0]||[],state=String(row[7]||""),sent=String(row[16]||""),failed=String(row[18]||"");if(state!=="delivery_in_progress"||sent!=="0"||failed!=="0")throw new Error("stale_fixture_postwrite_failed");return[{json:{row_number:p.row_number,before:p.before,after:{state,files_sent:sent,files_failed:failed},verified_message_ids:p.verified_message_ids,updated_range:$("Write Controlled Stale Canonical State").first().json.updatedRange||""}}];` } };
  const nodes = [trigger, read, prepare, write, reread, verify], connections = {}; for (let i = 0; i < nodes.length - 1; i++) connections[nodes[i].name] = edge(nodes[i + 1].name);
  const workflow = await api("/workflows", { method: "POST", body: JSON.stringify({ name: "Temporary Verified Stale Zero-Recovery Fixture", nodes, connections, settings: { executionOrder: "v1", saveDataSuccessExecution: "all", saveDataErrorExecution: "all" } }) });
  try { await api(`/workflows/${workflow.id}/activate`, { method: "POST" }); const response = await fetch(`http://localhost:5678/webhook/${route}`, { method: "POST" }); const body = await response.text(); if (!response.ok) throw new Error(`stale fixture ${response.status}: ${body.slice(0, 700)}`); const output = { workflow_id: workflow.id, result: JSON.parse(body) }; const outPath = path.join(ROOT, "n8n", "exports", "proya-delivery-log-audit-20260806T1125CST", "zero-recovery-stale-fixture.json"); fs.writeFileSync(outPath, JSON.stringify(output, null, 2) + "\n"); process.stdout.write(JSON.stringify(output, null, 2) + "\n"); }
  finally { try { await api(`/workflows/${workflow.id}/deactivate`, { method: "POST" }); } catch {} try { await api(`/workflows/${workflow.id}`, { method: "DELETE" }); } catch {} }
})().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exitCode = 1; });
