"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
const API = "http://localhost:5678/api/v1";
const SHEET = "1eyA1XRNZU0usuii801IrJCJHp8oCh2XjlfROrzzvpwE";
const PHONE = "6281120262823", CONVERSATION = "wa:6281120262823", BATCH = "6916";
const env = Object.fromEntries(fs.readFileSync(path.join(ROOT, ".env"), "utf8").split(/\r?\n/).map((line) => { const i = line.indexOf("="); return i > 0 ? [line.slice(0, i), line.slice(i + 1)] : ["", ""]; }).filter(([key]) => key));
const id = () => crypto.randomUUID(); const edge = (node) => ({ main: [[{ node, type: "main", index: 0 }]] });
async function api(route, options = {}) { const response = await fetch(API + route, { ...options, headers: { "X-N8N-API-KEY": env.N8N_API_KEY, ...(options.body ? { "Content-Type": "application/json" } : {}) } }); const body = await response.text(); if (!response.ok) throw new Error(`n8n API ${response.status} ${route}: ${body.slice(0, 700)}`); return body ? JSON.parse(body) : {}; }

(async () => {
  const delivery = await api("/workflows/AffWaDelivery2026"); const credential = delivery.nodes.map((node) => node.credentials?.googleSheetsOAuth2Api).find(Boolean); if (!credential) throw new Error("credential missing");
  const route = `zero-recovery-write-failure-${id()}`;
  const trigger = { id: id(), name: "Run Controlled Persistence Failure", type: "n8n-nodes-base.webhook", typeVersion: 2.1, position: [-660, 0], webhookId: id(), parameters: { httpMethod: "POST", path: route, responseMode: "lastNode", options: {} } };
  const read = { id: id(), name: "Read Durable Recovery Preconditions", type: "n8n-nodes-base.httpRequest", typeVersion: 4.4, position: [-440, 0], credentials: { googleSheetsOAuth2Api: credential }, parameters: { authentication: "predefinedCredentialType", nodeCredentialType: "googleSheetsOAuth2Api", url: `https://sheets.googleapis.com/v4/spreadsheets/${SHEET}/values:batchGet?${["WhatsApp Leads!A:AE", "Delivery Log!A:R", "WhatsApp Message Log!A:X"].map((r) => `ranges=${encodeURIComponent(r)}`).join("&")}`, options: { timeout: 45000 } } };
  const code = `const PHONE=${JSON.stringify(PHONE)},CONV=${JSON.stringify(CONVERSATION)},BATCH=${JSON.stringify(BATCH)},text=v=>v==null?"":String(v).trim(),digits=v=>text(v).replace(/\\D/g,"");function table(v){const h=(v?.[0]||[]).map(text);return{headers:h,rows:(v||[]).slice(1).map((r,i)=>({row_number:i+2,...Object.fromEntries(h.map((n,c)=>[n,text(r[c])]))})).filter(r=>Object.values(r).some(text))}}const ranges=$json.valueRanges||[],leads=table(ranges[0]?.values),delivery=table(ranges[1]?.values),messages=table(ranges[2]?.values),match=leads.rows.filter(r=>r.conversation_id===CONV&&digits(r.wa_id||r.whatsapp_number)===PHONE&&r.batch_number===BATCH);if(match.length!==1)throw new Error("failure_fixture_lead_not_unique");const lead=match[0],detail=delivery.rows.filter(r=>r.conversation_id===CONV&&r.batch_number===BATCH&&digits(r.whatsapp_number)===PHONE),valid=detail.filter(r=>/^wamid\\./.test(r.whatsapp_message_id)&&["accepted","sent","delivered","read"].includes(r.delivery_state||r.state||r.send_state)),messageIds=new Set(valid.map(r=>r.whatsapp_message_id));if(detail.length!==15||new Set(valid.map(r=>r.delivery_key)).size!==15||messageIds.size!==15||detail.some(r=>r.last_error))throw new Error("failure_fixture_15_id_precondition_failed");const msg=messages.rows.filter(r=>r.conversation_id===CONV||digits(r.recipient_number||r.whatsapp_number)===PHONE);if(new Set(msg.map(r=>r.whatsapp_message_id||r.message_id).filter(v=>/^wamid\\./.test(v))).size!==15)throw new Error("failure_fixture_message_log_precondition_failed");const record={...lead,state:"files_sent",files_expected:"15",files_sent:"15",files_failed:"0",last_error:"",updated_at:new Date().toISOString()};return[{json:{row_number:lead.row_number,lead_row_values:leads.headers.map(h=>text(record[h])),verified_message_ids:15,before_state:lead.state,before_sent:lead.files_sent}}];`;
  const prepare = { id: id(), name: "Build Verified Final State Payload", type: "n8n-nodes-base.code", typeVersion: 2, position: [-220, 0], parameters: { jsCode: code } };
  const fail = { id: id(), name: "Update Final Send State - Controlled Failure", type: "n8n-nodes-base.httpRequest", typeVersion: 4.4, position: [0, 0], credentials: { googleSheetsOAuth2Api: credential }, parameters: { authentication: "predefinedCredentialType", nodeCredentialType: "googleSheetsOAuth2Api", method: "PUT", url: "https://sheets.googleapis.com/v4/spreadsheets/CONTROLLED-NONEXISTENT-SPREADSHEET/values/WhatsApp%20Leads!A98%3AAE98?valueInputOption=RAW", sendBody: true, specifyBody: "json", jsonBody: "={{ JSON.stringify({majorDimension:'ROWS',values:[$json.lead_row_values]}) }}", options: { timeout: 45000 } } };
  const nodes = [trigger, read, prepare, fail], connections = { [trigger.name]: edge(read.name), [read.name]: edge(prepare.name), [prepare.name]: edge(fail.name) };
  const workflow = await api("/workflows", { method: "POST", body: JSON.stringify({ name: "Temporary Zero-Recovery Persistence Failure", nodes, connections, settings: { executionOrder: "v1", saveDataSuccessExecution: "all", saveDataErrorExecution: "all" } }) });
  await api(`/workflows/${workflow.id}/activate`, { method: "POST" });
  const response = await fetch(`http://localhost:5678/webhook/${route}`, { method: "POST" }); const body = await response.text();
  await api(`/workflows/${workflow.id}/deactivate`, { method: "POST" });
  const output = { workflow_id: workflow.id, route, http_status: response.status, response: body.slice(0, 1000), expected_failure: response.status >= 400, media_nodes_present: false, cleanup_pending: true };
  const outPath = path.join(ROOT, "n8n", "exports", "proya-delivery-log-audit-20260806T1125CST", "zero-recovery-persistence-failure-launch.json"); fs.writeFileSync(outPath, JSON.stringify(output, null, 2) + "\n"); process.stdout.write(JSON.stringify(output, null, 2) + "\n");
  if (response.status < 400) throw new Error("controlled persistence failure unexpectedly succeeded");
})().catch((error) => { process.stderr.write(`${error.stack || error.message}\n`); process.exitCode = 1; });
