"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
const API = "http://localhost:5678/api/v1";
const OLD_SHEET = "1eyA1XRNZU0usuii801IrJCJHp8oCh2XjlfROrzzvpwE";
const NEW_SHEET = "1Zsq-ngyC1RGOCLlibFI-UyPBW88oQc0aJhC5cxtbrzA";
const env = Object.fromEntries(fs.readFileSync(path.join(ROOT, ".env"), "utf8").split(/\r?\n/).map(line => { const i=line.indexOf("="); return i>0?[line.slice(0,i),line.slice(i+1)]:["",""]; }).filter(([key])=>key));
const id=()=>crypto.randomUUID();
async function api(route,options={}){const response=await fetch(API+route,{...options,headers:{"X-N8N-API-KEY":env.N8N_API_KEY,...(options.body?{"Content-Type":"application/json"}:{})}});const body=await response.text();if(!response.ok)throw new Error(`n8n API ${response.status} ${route}: ${body.slice(0,500)}`);return body?JSON.parse(body):{};}
const connect=name=>({main:[[{node:name,type:"main",index:0}]]});

async function main(){
  const delivery=await api("/workflows/AffWaDelivery2026"),credential=delivery.nodes.map(node=>node.credentials?.googleSheetsOAuth2Api).find(Boolean);if(!credential)throw new Error("Production Google Sheets credential missing");
  const route=`google-oauth-production-probe-${crypto.randomUUID()}`;
  const trigger={id:id(),name:"Production Credential Probe",type:"n8n-nodes-base.webhook",typeVersion:2.1,position:[-900,0],webhookId:id(),parameters:{httpMethod:"POST",path:route,responseMode:"lastNode",options:{}}};
  const read={id:id(),name:"Read Production Lead and Dedup Sheets",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[-680,0],credentials:{googleSheetsOAuth2Api:credential},parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",url:`https://sheets.googleapis.com/v4/spreadsheets/${OLD_SHEET}/values:batchGet?ranges=${encodeURIComponent("WhatsApp Leads!A:AE")}&ranges=${encodeURIComponent("WhatsApp Raw Events!A:L")}`,options:{timeout:45000}},retryOnFail:true,maxTries:3,waitBetweenTries:2000};
  const prepare={id:id(),name:"Validate Reads and Prepare Test Write",type:"n8n-nodes-base.code",typeVersion:2,position:[-460,0],parameters:{jsCode:`const ranges=$json.valueRanges||[];if(ranges.length!==2)throw new Error("credential_probe_missing_ranges");const lead=ranges[0]?.values||[],raw=ranges[1]?.values||[];if(!lead.length||!raw.length)throw new Error("credential_probe_headers_missing");const sentAt=new Date(Date.now()+7*60*60*1000).toISOString().slice(0,19).replace("T"," ")+" WIB";return[{json:{lead_range:ranges[0].range,lead_rows:Math.max(0,lead.length-1),dedup_range:ranges[1].range,dedup_rows:Math.max(0,raw.length-1),row:[["999997","codex_credential_probe","6200000000001",sentAt,"0/15","Skipped","Controlled OAuth write probe; no WhatsApp request"]]}}];`}};
  const append={id:id(),name:"Write New Delivery Log Probe Row",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[-240,0],credentials:{googleSheetsOAuth2Api:credential},parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",method:"POST",url:`https://sheets.googleapis.com/v4/spreadsheets/${NEW_SHEET}/values/%27Delivery%20Log%27!A%3AG:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,sendBody:true,specifyBody:"json",jsonBody:'={{ JSON.stringify({majorDimension:"ROWS",values:$json.row}) }}',options:{timeout:45000}},retryOnFail:true,maxTries:3,waitBetweenTries:2000};
  const capture={id:id(),name:"Capture Probe Row",type:"n8n-nodes-base.code",typeVersion:2,position:[-20,0],parameters:{jsCode:`const source=$("Validate Reads and Prepare Test Write").first().json,range=String($json?.updates?.updatedRange||"");if(!range)throw new Error("credential_probe_write_range_missing");return[{json:{...source,updated_range:range,updated_rows:$json?.updates?.updatedRows||0,encoded_range:encodeURIComponent(range)}}];`}};
  const clear={id:id(),name:"Remove New Delivery Log Probe Row",type:"n8n-nodes-base.httpRequest",typeVersion:4.4,position:[200,0],credentials:{googleSheetsOAuth2Api:credential},parameters:{authentication:"predefinedCredentialType",nodeCredentialType:"googleSheetsOAuth2Api",method:"POST",url:`=https://sheets.googleapis.com/v4/spreadsheets/${NEW_SHEET}/values/{{$json.encoded_range}}:clear`,sendBody:true,specifyBody:"json",jsonBody:"={{ JSON.stringify({}) }}",options:{timeout:45000}},retryOnFail:true,maxTries:3,waitBetweenTries:2000};
  const result={id:id(),name:"Credential Probe Result",type:"n8n-nodes-base.code",typeVersion:2,position:[420,0],parameters:{jsCode:`const s=$("Capture Probe Row").first().json;return[{json:{credential_name:"Google Sheets account",lead_read:{range:s.lead_range,rows:s.lead_rows},dedup_read:{range:s.dedup_range,rows:s.dedup_rows},write:{spreadsheet_id:"${NEW_SHEET}",updated_range:s.updated_range,updated_rows:s.updated_rows},cleanup:{cleared_range:$json.clearedRange||s.updated_range},active_workflow_execution:true}}];`}};
  const nodes=[trigger,read,prepare,append,capture,clear,result],connections={};for(let i=0;i<nodes.length-1;i++)connections[nodes[i].name]=connect(nodes[i+1].name);
  const workflow=await api("/workflows",{method:"POST",body:JSON.stringify({name:"Temporary Active Production Google OAuth Probe",nodes,connections,settings:{executionOrder:"v1",saveDataSuccessExecution:"all",saveDataErrorExecution:"all"}})});
  try{await api(`/workflows/${workflow.id}/activate`,{method:"POST"});const response=await fetch(`http://localhost:5678/webhook/${route}`,{method:"POST"}),body=await response.text();if(!response.ok)throw new Error(`credential probe ${response.status}: ${body.slice(0,500)}`);const output={workflow_id:workflow.id,result:JSON.parse(body)};fs.writeFileSync(path.join(ROOT,"n8n","exports","proya-delivery-log-audit-20260806T1125CST","google-oauth-production-probe.json"),JSON.stringify(output,null,2)+"\n");process.stdout.write(JSON.stringify(output,null,2)+"\n");}
  finally{try{await api(`/workflows/${workflow.id}/deactivate`,{method:"POST"});}catch{}try{await api(`/workflows/${workflow.id}`,{method:"DELETE"});}catch{}}
}
main().catch(error=>{process.stderr.write((error.stack||error.message)+"\n");process.exitCode=1;});
